/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2210 from the
 * contents of TextUI.xs. Do not edit this file, edit TextUI.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "TextUI.xs"
#include "module.h"

void perl_statusbar_init(void);
void perl_statusbar_deinit(void);

static int initialized = FALSE;

static void perl_main_window_fill_hash(HV *hv, MAIN_WINDOW_REC *window)
{
	hv_store(hv, "active", 6, plain_bless(window->active, "Irssi::UI::Window"), 0);

	hv_store(hv, "first_line", 10, newSViv(window->first_line), 0);
	hv_store(hv, "last_line", 9, newSViv(window->last_line), 0);
	hv_store(hv, "width", 5, newSViv(window->width), 0);
	hv_store(hv, "height", 6, newSViv(window->height), 0);

	hv_store(hv, "statusbar_lines", 15, newSViv(window->statusbar_lines), 0);
}

static void perl_text_buffer_fill_hash(HV *hv, TEXT_BUFFER_REC *buffer)
{
	hv_store(hv, "first_line", 10, plain_bless(buffer->first_line, "Irssi::TextUI::Line"), 0);
	hv_store(hv, "lines_count", 11, newSViv(buffer->lines_count), 0);
	hv_store(hv, "cur_line", 8, plain_bless(buffer->cur_line, "Irssi::TextUI::Line"), 0);
	hv_store(hv, "last_eol", 8, newSViv(buffer->last_eol), 0);
}

static void perl_text_buffer_view_fill_hash(HV *hv, TEXT_BUFFER_VIEW_REC *view)
{
	hv_store(hv, "buffer", 6, plain_bless(view->buffer, "Irssi::TextUI::TextBuffer"), 0);
	hv_store(hv, "width", 5, newSViv(view->width), 0);
	hv_store(hv, "height", 6, newSViv(view->height), 0);

	hv_store(hv, "default_indent", 14, newSViv(view->default_indent), 0);
	hv_store(hv, "longword_noindent", 17, newSViv(view->longword_noindent), 0);
	hv_store(hv, "scroll", 6, newSViv(view->scroll), 0);

	hv_store(hv, "ypos", 4, newSViv(view->ypos), 0);

	hv_store(hv, "startline", 9, plain_bless(view->startline, "Irssi::TextUI::Line"), 0);
	hv_store(hv, "subline", 7, newSViv(view->subline), 0);

	hv_store(hv, "bottom_startline", 16, plain_bless(view->bottom_startline, "Irssi::TextUI::Line"), 0);
	hv_store(hv, "bottom_subline", 14, newSViv(view->bottom_subline), 0);

	hv_store(hv, "empty_linecount", 15, newSViv(view->empty_linecount), 0);
	hv_store(hv, "bottom", 6, newSViv(view->bottom), 0);
}

static void perl_line_fill_hash(HV *hv, LINE_REC *line)
{
	hv_store(hv, "info", 4, plain_bless(&line->info, "Irssi::TextUI::LineInfo"), 0);
}

static void perl_line_cache_fill_hash(HV *hv, LINE_CACHE_REC *cache)
{
	hv_store(hv, "last_access", 11, newSViv(cache->last_access), 0);
	hv_store(hv, "count", 5, newSViv(cache->count), 0);
	/*LINE_CACHE_SUB_REC lines[1];*/
}

static void perl_line_info_fill_hash(HV *hv, LINE_INFO_REC *info)
{
	hv_store(hv, "level", 5, newSViv(info->level), 0);
	hv_store(hv, "time", 4, newSViv(info->time), 0);
}

static void perl_statusbar_item_fill_hash(HV *hv, SBAR_ITEM_REC *item)
{
	hv_store(hv, "min_size", 8, newSViv(item->min_size), 0);
	hv_store(hv, "max_size", 8, newSViv(item->max_size), 0);
	hv_store(hv, "xpos", 4, newSViv(item->xpos), 0);
	hv_store(hv, "size", 4, newSViv(item->size), 0);
	if (item->bar->parent_window != NULL)
		hv_store(hv, "window", 6, plain_bless(item->bar->parent_window->active, "Irssi::UI::Window"), 0);
}

static PLAIN_OBJECT_INIT_REC textui_plains[] = {
	{ "Irssi::TextUI::MainWindow", (PERL_OBJECT_FUNC) perl_main_window_fill_hash },
	{ "Irssi::TextUI::TextBuffer", (PERL_OBJECT_FUNC) perl_text_buffer_fill_hash },
	{ "Irssi::TextUI::TextBufferView", (PERL_OBJECT_FUNC) perl_text_buffer_view_fill_hash },
	{ "Irssi::TextUI::Line", (PERL_OBJECT_FUNC) perl_line_fill_hash },
	{ "Irssi::TextUI::LineCache", (PERL_OBJECT_FUNC) perl_line_cache_fill_hash },
	{ "Irssi::TextUI::LineInfo", (PERL_OBJECT_FUNC) perl_line_info_fill_hash },
	{ "Irssi::TextUI::StatusbarItem", (PERL_OBJECT_FUNC) perl_statusbar_item_fill_hash },

	{ NULL, NULL }
};

#line 100 "TextUI.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 152 "TextUI.c"

XS(XS_Irssi__TextUI_init); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__TextUI_init)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
#line 97 "TextUI.xs"
	if (initialized) return;
	perl_api_version_check("Irssi::TextUI");
	initialized = TRUE;

        irssi_add_plains(textui_plains);
        perl_statusbar_init();
#line 172 "TextUI.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__TextUI_deinit); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__TextUI_deinit)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
#line 107 "TextUI.xs"
	if (!initialized) return;
        perl_statusbar_deinit();
	initialized = FALSE;
#line 193 "TextUI.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi_gui_printtext); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_gui_printtext)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       croak_xs_usage(cv,  "xpos, ypos, str");
    {
	int	xpos = (int)SvIV(ST(0));
	int	ypos = (int)SvIV(ST(1));
	char *	str = (char *)SvPV_nolen(ST(2));

	gui_printtext(xpos, ypos, str);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi_gui_input_set); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_gui_input_set)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "str");
    {
	char *	str = (char *)SvPV_nolen(ST(0));
#line 123 "TextUI.xs"
	gui_entry_set_text(active_entry, str);
#line 234 "TextUI.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi_gui_input_get_pos); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_gui_input_get_pos)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 128 "TextUI.xs"
	RETVAL = gui_entry_get_pos(active_entry);
#line 255 "TextUI.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_gui_input_set_pos); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_gui_input_set_pos)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "pos");
    {
	int	pos = (int)SvIV(ST(0));
#line 136 "TextUI.xs"
	gui_entry_set_pos(active_entry, pos);
#line 276 "TextUI.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__UI__Window_print_after); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI__Window_print_after)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 4)
       croak_xs_usage(cv,  "window, prev, level, str");
    {
	Irssi__UI__Window	window = irssi_ref_object(ST(0));
	Irssi__TextUI__Line	prev = irssi_ref_object(ST(1));
	int	level = (int)SvIV(ST(2));
	char *	str = (char *)SvPV_nolen(ST(3));
#line 147 "TextUI.xs"
	TEXT_DEST_REC dest;
	char *text;
	char *text2;
#line 301 "TextUI.c"
#line 151 "TextUI.xs"
	format_create_dest(&dest, NULL, NULL, level, window);
	text = format_string_expand(str, NULL);
	text2 = g_strconcat(text, "\n", NULL);
	gui_printtext_after(&dest, prev, text2);
	g_free(text);
	g_free(text2);
#line 309 "TextUI.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__UI__Window_gui_printtext_after); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI__Window_gui_printtext_after)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 4)
       croak_xs_usage(cv,  "window, prev, level, str");
    {
	Irssi__UI__Window	window = irssi_ref_object(ST(0));
	Irssi__TextUI__Line	prev = irssi_ref_object(ST(1));
	int	level = (int)SvIV(ST(2));
	char *	str = (char *)SvPV_nolen(ST(3));
#line 165 "TextUI.xs"
	TEXT_DEST_REC dest;
#line 332 "TextUI.c"
#line 167 "TextUI.xs"
	format_create_dest(&dest, NULL, NULL, level, window);
	gui_printtext_after(&dest, prev, str);
#line 336 "TextUI.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__UI__Window_last_line_insert); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI__Window_last_line_insert)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "window");
    {
	Irssi__UI__Window	window = irssi_ref_object(ST(0));
	Irssi__TextUI__Line	RETVAL;
#line 174 "TextUI.xs"
	RETVAL = WINDOW_GUI(window)->insert_after;
#line 357 "TextUI.c"
	ST(0) = plain_bless(RETVAL, "Irssi::TextUI::Line");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi__UI__Server_gui_printtext_after); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI__Server_gui_printtext_after)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 5)
       croak_xs_usage(cv,  "server, target, prev, level, str");
    {
	Irssi__Server	server = irssi_ref_object(ST(0));
	char *	target = (char *)SvPV_nolen(ST(1));
	Irssi__TextUI__Line	prev = irssi_ref_object(ST(2));
	int	level = (int)SvIV(ST(3));
	char *	str = (char *)SvPV_nolen(ST(4));
#line 188 "TextUI.xs"
	TEXT_DEST_REC dest;
#line 384 "TextUI.c"
#line 190 "TextUI.xs"
	format_create_dest(&dest, server, target, level, NULL);
	gui_printtext_after(&dest, prev, str);
#line 388 "TextUI.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__UI__Server_term_refresh_freeze); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI__Server_term_refresh_freeze)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {

	term_refresh_freeze();
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__UI__Server_term_refresh_thaw); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI__Server_term_refresh_thaw)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {

	term_refresh_thaw();
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Irssi__TextUI); /* prototype to pass -Wmissing-prototypes */
XS(boot_Irssi__TextUI)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK ;

        (void)newXSproto_portable("Irssi::TextUI::init", XS_Irssi__TextUI_init, file, "");
        (void)newXSproto_portable("Irssi::TextUI::deinit", XS_Irssi__TextUI_deinit, file, "");
        (void)newXSproto_portable("Irssi::gui_printtext", XS_Irssi_gui_printtext, file, "$$$");
        (void)newXSproto_portable("Irssi::gui_input_set", XS_Irssi_gui_input_set, file, "$");
        (void)newXSproto_portable("Irssi::gui_input_get_pos", XS_Irssi_gui_input_get_pos, file, "");
        (void)newXSproto_portable("Irssi::gui_input_set_pos", XS_Irssi_gui_input_set_pos, file, "$");
        (void)newXSproto_portable("Irssi::UI::Window::print_after", XS_Irssi__UI__Window_print_after, file, "$$$$");
        (void)newXSproto_portable("Irssi::UI::Window::gui_printtext_after", XS_Irssi__UI__Window_gui_printtext_after, file, "$$$$");
        (void)newXSproto_portable("Irssi::UI::Window::last_line_insert", XS_Irssi__UI__Window_last_line_insert, file, "$");
        (void)newXSproto_portable("Irssi::UI::Server::gui_printtext_after", XS_Irssi__UI__Server_gui_printtext_after, file, "$$$$$");
        (void)newXSproto_portable("Irssi::UI::Server::term_refresh_freeze", XS_Irssi__UI__Server_term_refresh_freeze, file, "");
        (void)newXSproto_portable("Irssi::UI::Server::term_refresh_thaw", XS_Irssi__UI__Server_term_refresh_thaw, file, "");

    /* Initialisation Section */

#line 194 "TextUI.xs"
	irssi_boot(TextUI__Statusbar);
	irssi_boot(TextUI__TextBuffer);
	irssi_boot(TextUI__TextBufferView);

#line 473 "TextUI.c"

    /* End of Initialisation Section */

#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

