/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2210 from the
 * contents of TextBufferView.xs. Do not edit this file, edit TextBufferView.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "TextBufferView.xs"
#include "module.h"

#line 13 "TextBufferView.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 65 "TextBufferView.c"

XS(XS_Irssi__TextUI__TextBufferView_set_default_indent); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__TextUI__TextBufferView_set_default_indent)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       croak_xs_usage(cv,  "view, default_indent, longword_noindent");
    {
	Irssi__TextUI__TextBufferView	view = irssi_ref_object(ST(0));
	int	default_indent = (int)SvIV(ST(1));
	int	longword_noindent = (int)SvIV(ST(2));
#line 16 "TextBufferView.xs"
	textbuffer_view_set_default_indent(view, default_indent, longword_noindent, NULL);
#line 83 "TextBufferView.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__TextUI__TextBufferView_set_scroll); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__TextUI__TextBufferView_set_scroll)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "view, scroll");
    {
	Irssi__TextUI__TextBufferView	view = irssi_ref_object(ST(0));
	int	scroll = (int)SvIV(ST(1));

	textbuffer_view_set_scroll(view, scroll);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__TextUI__TextBufferView_clear); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__TextUI__TextBufferView_clear)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "view");
    {
	Irssi__TextUI__TextBufferView	view = irssi_ref_object(ST(0));

	textbuffer_view_clear(view);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__TextUI__TextBufferView_get_lines); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__TextUI__TextBufferView_get_lines)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "view");
    {
	Irssi__TextUI__TextBufferView	view = irssi_ref_object(ST(0));
	Irssi__TextUI__Line	RETVAL;

	RETVAL = textbuffer_view_get_lines(view);
	ST(0) = plain_bless(RETVAL, "Irssi::TextUI::Line");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi__TextUI__TextBufferView_scroll); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__TextUI__TextBufferView_scroll)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "view, lines");
    {
	Irssi__TextUI__TextBufferView	view = irssi_ref_object(ST(0));
	int	lines = (int)SvIV(ST(1));

	textbuffer_view_scroll(view, lines);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__TextUI__TextBufferView_scroll_line); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__TextUI__TextBufferView_scroll_line)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "view, line");
    {
	Irssi__TextUI__TextBufferView	view = irssi_ref_object(ST(0));
	Irssi__TextUI__Line	line = irssi_ref_object(ST(1));

	textbuffer_view_scroll_line(view, line);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__TextUI__TextBufferView_get_line_cache); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__TextUI__TextBufferView_get_line_cache)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "view, line");
    {
	Irssi__TextUI__TextBufferView	view = irssi_ref_object(ST(0));
	Irssi__TextUI__Line	line = irssi_ref_object(ST(1));
	Irssi__TextUI__LineCache	RETVAL;

	RETVAL = textbuffer_view_get_line_cache(view, line);
	ST(0) = plain_bless(RETVAL, "Irssi::TextUI::LineCache");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi__TextUI__TextBufferView_remove_line); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__TextUI__TextBufferView_remove_line)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "view, line");
    {
	Irssi__TextUI__TextBufferView	view = irssi_ref_object(ST(0));
	Irssi__TextUI__Line	line = irssi_ref_object(ST(1));

	textbuffer_view_remove_line(view, line);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__TextUI__TextBufferView_remove_all_lines); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__TextUI__TextBufferView_remove_all_lines)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "view");
    {
	Irssi__TextUI__TextBufferView	view = irssi_ref_object(ST(0));

	textbuffer_view_remove_all_lines(view);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__TextUI__TextBufferView_set_bookmark); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__TextUI__TextBufferView_set_bookmark)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       croak_xs_usage(cv,  "view, name, line");
    {
	Irssi__TextUI__TextBufferView	view = irssi_ref_object(ST(0));
	char *	name = (char *)SvPV_nolen(ST(1));
	Irssi__TextUI__Line	line = irssi_ref_object(ST(2));

	textbuffer_view_set_bookmark(view, name, line);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__TextUI__TextBufferView_set_bookmark_bottom); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__TextUI__TextBufferView_set_bookmark_bottom)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "view, name");
    {
	Irssi__TextUI__TextBufferView	view = irssi_ref_object(ST(0));
	char *	name = (char *)SvPV_nolen(ST(1));

	textbuffer_view_set_bookmark_bottom(view, name);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__TextUI__TextBufferView_get_bookmark); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__TextUI__TextBufferView_get_bookmark)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "view, name");
    {
	Irssi__TextUI__TextBufferView	view = irssi_ref_object(ST(0));
	char *	name = (char *)SvPV_nolen(ST(1));
	Irssi__TextUI__Line	RETVAL;

	RETVAL = textbuffer_view_get_bookmark(view, name);
	ST(0) = plain_bless(RETVAL, "Irssi::TextUI::Line");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi__TextUI__TextBufferView_redraw); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__TextUI__TextBufferView_redraw)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "view");
    {
	Irssi__TextUI__TextBufferView	view = irssi_ref_object(ST(0));

	textbuffer_view_redraw(view);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__UI__Window_view); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI__Window_view)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "window");
    {
	Irssi__UI__Window	window = irssi_ref_object(ST(0));
	Irssi__TextUI__TextBufferView	RETVAL;
#line 83 "TextBufferView.xs"
	RETVAL = WINDOW_GUI(window)->view;
#line 353 "TextBufferView.c"
	ST(0) = plain_bless(RETVAL, "Irssi::TextUI::TextBufferView");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Irssi__TextUI__TextBufferView); /* prototype to pass -Wmissing-prototypes */
XS(boot_Irssi__TextUI__TextBufferView)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK ;

        (void)newXSproto_portable("Irssi::TextUI::TextBufferView::set_default_indent", XS_Irssi__TextUI__TextBufferView_set_default_indent, file, "$$$");
        (void)newXSproto_portable("Irssi::TextUI::TextBufferView::set_scroll", XS_Irssi__TextUI__TextBufferView_set_scroll, file, "$$");
        (void)newXSproto_portable("Irssi::TextUI::TextBufferView::clear", XS_Irssi__TextUI__TextBufferView_clear, file, "$");
        (void)newXSproto_portable("Irssi::TextUI::TextBufferView::get_lines", XS_Irssi__TextUI__TextBufferView_get_lines, file, "$");
        (void)newXSproto_portable("Irssi::TextUI::TextBufferView::scroll", XS_Irssi__TextUI__TextBufferView_scroll, file, "$$");
        (void)newXSproto_portable("Irssi::TextUI::TextBufferView::scroll_line", XS_Irssi__TextUI__TextBufferView_scroll_line, file, "$$");
        (void)newXSproto_portable("Irssi::TextUI::TextBufferView::get_line_cache", XS_Irssi__TextUI__TextBufferView_get_line_cache, file, "$$");
        (void)newXSproto_portable("Irssi::TextUI::TextBufferView::remove_line", XS_Irssi__TextUI__TextBufferView_remove_line, file, "$$");
        (void)newXSproto_portable("Irssi::TextUI::TextBufferView::remove_all_lines", XS_Irssi__TextUI__TextBufferView_remove_all_lines, file, "$");
        (void)newXSproto_portable("Irssi::TextUI::TextBufferView::set_bookmark", XS_Irssi__TextUI__TextBufferView_set_bookmark, file, "$$$");
        (void)newXSproto_portable("Irssi::TextUI::TextBufferView::set_bookmark_bottom", XS_Irssi__TextUI__TextBufferView_set_bookmark_bottom, file, "$$");
        (void)newXSproto_portable("Irssi::TextUI::TextBufferView::get_bookmark", XS_Irssi__TextUI__TextBufferView_get_bookmark, file, "$$");
        (void)newXSproto_portable("Irssi::TextUI::TextBufferView::redraw", XS_Irssi__TextUI__TextBufferView_redraw, file, "$");
        (void)newXSproto_portable("Irssi::UI::Window::view", XS_Irssi__UI__Window_view, file, "$");
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

