/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2210 from the
 * contents of TextBuffer.xs. Do not edit this file, edit TextBuffer.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "TextBuffer.xs"
#include "module.h"

#line 13 "TextBuffer.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 65 "TextBuffer.c"

XS(XS_Irssi__TextUI__Line_prev); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__TextUI__Line_prev)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "line");
    {
	Irssi__TextUI__Line	line = irssi_ref_object(ST(0));
	Irssi__TextUI__Line	RETVAL;
#line 14 "TextBuffer.xs"
	RETVAL = line->prev;
#line 82 "TextBuffer.c"
	ST(0) = plain_bless(RETVAL, "Irssi::TextUI::Line");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi__TextUI__Line_next); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__TextUI__Line_next)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "line");
    {
	Irssi__TextUI__Line	line = irssi_ref_object(ST(0));
	Irssi__TextUI__Line	RETVAL;
#line 22 "TextBuffer.xs"
	RETVAL = line->next;
#line 106 "TextBuffer.c"
	ST(0) = plain_bless(RETVAL, "Irssi::TextUI::Line");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi__TextUI__Line_get_text); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__TextUI__Line_get_text)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "line, coloring");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	Irssi__TextUI__Line	line = irssi_ref_object(ST(0));
	int	coloring = (int)SvIV(ST(1));
#line 31 "TextBuffer.xs"
	GString *str;
	SV *result;
#line 133 "TextBuffer.c"
#line 34 "TextBuffer.xs"
	str = g_string_new(NULL);
	textbuffer_line2text(line, coloring, str);
	result = new_pv(str->str);
	XPUSHs(sv_2mortal(result));
	g_string_free(str, TRUE);
#line 140 "TextBuffer.c"
	PUTBACK;
	return;
    }
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Irssi__TextUI__TextBuffer); /* prototype to pass -Wmissing-prototypes */
XS(boot_Irssi__TextUI__TextBuffer)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK ;

        (void)newXSproto_portable("Irssi::TextUI::Line::prev", XS_Irssi__TextUI__Line_prev, file, "$");
        (void)newXSproto_portable("Irssi::TextUI::Line::next", XS_Irssi__TextUI__Line_next, file, "$");
        (void)newXSproto_portable("Irssi::TextUI::Line::get_text", XS_Irssi__TextUI__Line_get_text, file, "$$");
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

