/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2210 from the
 * contents of Channel.xs. Do not edit this file, edit Channel.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Channel.xs"
#include "module.h"

#line 13 "Channel.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 65 "Channel.c"

XS(XS_Irssi__Irc_get_mask); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc_get_mask)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       croak_xs_usage(cv,  "nick, address, flags");
    {
	char *	nick = (char *)SvPV_nolen(ST(0));
	char *	address = (char *)SvPV_nolen(ST(1));
	int	flags = (int)SvIV(ST(2));
	char *	RETVAL;
	dXSTARG;

	RETVAL = irc_get_mask(nick, address, flags);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Irssi__Irc_MASK_NICK); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc_MASK_NICK)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 15 "Channel.xs"
	RETVAL = IRC_MASK_NICK;
#line 106 "Channel.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi__Irc_MASK_USER); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc_MASK_USER)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 22 "Channel.xs"
	RETVAL = IRC_MASK_USER;
#line 128 "Channel.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi__Irc_MASK_HOST); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc_MASK_HOST)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 29 "Channel.xs"
	RETVAL = IRC_MASK_HOST;
#line 150 "Channel.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi__Irc_MASK_DOMAIN); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc_MASK_DOMAIN)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 36 "Channel.xs"
	RETVAL = IRC_MASK_DOMAIN;
#line 172 "Channel.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi__Irc__Channel_bans); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc__Channel_bans)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "channel");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	Irssi__Irc__Channel	channel = irssi_ref_object(ST(0));
#line 46 "Channel.xs"
	GSList *tmp;
#line 195 "Channel.c"
#line 48 "Channel.xs"
	for (tmp = channel->banlist; tmp != NULL; tmp = tmp->next) {
		XPUSHs(sv_2mortal(plain_bless(tmp->data, "Irssi::Irc::Ban")));
	}
#line 200 "Channel.c"
	PUTBACK;
	return;
    }
}


XS(XS_Irssi__Irc__Channel_nick_insert); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc__Channel_nick_insert)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 6)
       croak_xs_usage(cv,  "channel, nick, op, halfop, voice, send_massjoin");
    {
	Irssi__Irc__Channel	channel = irssi_ref_object(ST(0));
	char *	nick = (char *)SvPV_nolen(ST(1));
	int	op = (int)SvIV(ST(2));
	int	halfop = (int)SvIV(ST(3));
	int	voice = (int)SvIV(ST(4));
	int	send_massjoin = (int)SvIV(ST(5));
	Irssi__Irc__Nick	RETVAL;
#line 61 "Channel.xs"
	RETVAL = irc_nicklist_insert(channel, nick, op, halfop, voice, send_massjoin, NULL);
#line 227 "Channel.c"
	ST(0) = iobject_bless((SERVER_REC *)RETVAL);

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Irssi__Irc__Channel); /* prototype to pass -Wmissing-prototypes */
XS(boot_Irssi__Irc__Channel)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK ;

        (void)newXSproto_portable("Irssi::Irc::get_mask", XS_Irssi__Irc_get_mask, file, "$$$");
        (void)newXSproto_portable("Irssi::Irc::MASK_NICK", XS_Irssi__Irc_MASK_NICK, file, "");
        (void)newXSproto_portable("Irssi::Irc::MASK_USER", XS_Irssi__Irc_MASK_USER, file, "");
        (void)newXSproto_portable("Irssi::Irc::MASK_HOST", XS_Irssi__Irc_MASK_HOST, file, "");
        (void)newXSproto_portable("Irssi::Irc::MASK_DOMAIN", XS_Irssi__Irc_MASK_DOMAIN, file, "");
        (void)newXSproto_portable("Irssi::Irc::Channel::bans", XS_Irssi__Irc__Channel_bans, file, "$");
        (void)newXSproto_portable("Irssi::Irc::Channel::nick_insert", XS_Irssi__Irc__Channel_nick_insert, file, "$$$$$$");
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

