/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2210 from the
 * contents of Dcc.xs. Do not edit this file, edit Dcc.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Dcc.xs"
#include "module.h"

#line 13 "Dcc.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 65 "Dcc.c"

XS(XS_Irssi__Irc_dccs); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc_dccs)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 9 "Dcc.xs"
	GSList *tmp;
#line 82 "Dcc.c"
#line 11 "Dcc.xs"
	for (tmp = dcc_conns; tmp != NULL; tmp = tmp->next) 
		XPUSHs(sv_2mortal(simple_iobject_bless((DCC_REC *) tmp->data)));
#line 86 "Dcc.c"
	PUTBACK;
	return;
    }
}


XS(XS_Irssi__Irc_dcc_register_type); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc_dcc_register_type)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "type");
    {
	char *	type = (char *)SvPV_nolen(ST(0));

	dcc_register_type(type);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Irc_dcc_unregister_type); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc_dcc_unregister_type)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "type");
    {
	char *	type = (char *)SvPV_nolen(ST(0));

	dcc_unregister_type(type);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Irc_dcc_str2type); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc_dcc_str2type)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "str");
    {
	char *	str = (char *)SvPV_nolen(ST(0));
	int	RETVAL;
	dXSTARG;

	RETVAL = dcc_str2type(str);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi__Irc_dcc_type2str); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc_dcc_type2str)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "type");
    {
	int	type = (int)SvIV(ST(0));
	char *	RETVAL;
	dXSTARG;
#line 30 "Dcc.xs"
	RETVAL = (char *) module_find_id_str("DCC", type);
#line 169 "Dcc.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Irssi__Irc_dcc_find_request_latest); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc_dcc_find_request_latest)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "type");
    {
	int	type = (int)SvIV(ST(0));
	Irssi__Irc__Dcc	RETVAL;

	RETVAL = dcc_find_request_latest(type);
	ST(0) = simple_iobject_bless((DCC_REC *)RETVAL);

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi__Irc_dcc_find_request); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc_dcc_find_request)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       croak_xs_usage(cv,  "type, nick, arg");
    {
	int	type = (int)SvIV(ST(0));
	char *	nick = (char *)SvPV_nolen(ST(1));
	char *	arg = (char *)SvPV_nolen(ST(2));
	Irssi__Irc__Dcc	RETVAL;

	RETVAL = dcc_find_request(type, nick, arg);
	ST(0) = simple_iobject_bless((DCC_REC *)RETVAL);

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi__Irc_dcc_chat_find_id); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc_dcc_chat_find_id)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "id");
    {
	char *	id = (char *)SvPV_nolen(ST(0));
	Irssi__Irc__Dcc__Chat	RETVAL;

	RETVAL = dcc_chat_find_id(id);
	ST(0) = simple_iobject_bless((DCC_REC *)RETVAL);

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi__Irc_dcc_chat_send); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc_dcc_chat_send)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "dcc, data");
    {
	Irssi__Irc__Dcc__Chat	dcc = irssi_ref_object(ST(0));
	char *	data = (char *)SvPV_nolen(ST(1));

	dcc_chat_send(dcc, data);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Irc_dcc_ctcp_message); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc_dcc_ctcp_message)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 5)
       croak_xs_usage(cv,  "server, target, chat, notice, msg");
    {
	Irssi__Irc__Server	server = irssi_ref_object(ST(0));
	char *	target = (char *)SvPV_nolen(ST(1));
	Irssi__Irc__Dcc__Chat	chat = irssi_ref_object(ST(2));
	int	notice = (int)SvIV(ST(3));
	char *	msg = (char *)SvPV_nolen(ST(4));

	dcc_ctcp_message(server, target, chat, notice, msg);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Irc_dcc_get_download_path); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc_dcc_get_download_path)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "fname");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	char *	fname = (char *)SvPV_nolen(ST(0));
#line 65 "Dcc.xs"
	char *ret;
#line 306 "Dcc.c"
#line 67 "Dcc.xs"
	ret = dcc_get_download_path(fname);
	XPUSHs(sv_2mortal(new_pv(ret)));
	g_free(ret);
#line 311 "Dcc.c"
	PUTBACK;
	return;
    }
}


XS(XS_Irssi__Irc__Dcc_init_rec); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc__Dcc_init_rec)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 5)
       croak_xs_usage(cv,  "dcc, server, chat, nick, arg");
    {
	Irssi__Irc__Dcc	dcc = irssi_ref_object(ST(0));
	Irssi__Irc__Server	server = irssi_ref_object(ST(1));
	Irssi__Irc__Dcc__Chat	chat = irssi_ref_object(ST(2));
	char *	nick = (char *)SvPV_nolen(ST(3));
	char *	arg = (char *)SvPV_nolen(ST(4));

	dcc_init_rec(dcc, server, chat, nick, arg);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Irc__Dcc_destroy); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc__Dcc_destroy)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "dcc");
    {
	Irssi__Irc__Dcc	dcc = irssi_ref_object(ST(0));

	dcc_destroy(dcc);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Irc__Dcc_close); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc__Dcc_close)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "dcc");
    {
	Irssi__Irc__Dcc	dcc = irssi_ref_object(ST(0));

	dcc_close(dcc);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Irc__Dcc_reject); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc__Dcc_reject)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "dcc, server");
    {
	Irssi__Irc__Dcc	dcc = irssi_ref_object(ST(0));
	Irssi__Irc__Server	server = irssi_ref_object(ST(1));

	dcc_reject(dcc, server);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Windowitem_get_dcc); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Windowitem_get_dcc)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "item");
    {
	Irssi__Windowitem	item = irssi_ref_object(ST(0));
	Irssi__Irc__Dcc__Chat	RETVAL;

	RETVAL = item_get_dcc(item);
	ST(0) = simple_iobject_bless((DCC_REC *)RETVAL);

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Irssi__Irc__Dcc); /* prototype to pass -Wmissing-prototypes */
XS(boot_Irssi__Irc__Dcc)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK ;

        (void)newXSproto_portable("Irssi::Irc::dccs", XS_Irssi__Irc_dccs, file, "");
        (void)newXSproto_portable("Irssi::Irc::dcc_register_type", XS_Irssi__Irc_dcc_register_type, file, "$");
        (void)newXSproto_portable("Irssi::Irc::dcc_unregister_type", XS_Irssi__Irc_dcc_unregister_type, file, "$");
        (void)newXSproto_portable("Irssi::Irc::dcc_str2type", XS_Irssi__Irc_dcc_str2type, file, "$");
        (void)newXSproto_portable("Irssi::Irc::dcc_type2str", XS_Irssi__Irc_dcc_type2str, file, "$");
        (void)newXSproto_portable("Irssi::Irc::dcc_find_request_latest", XS_Irssi__Irc_dcc_find_request_latest, file, "$");
        (void)newXSproto_portable("Irssi::Irc::dcc_find_request", XS_Irssi__Irc_dcc_find_request, file, "$$$");
        (void)newXSproto_portable("Irssi::Irc::dcc_chat_find_id", XS_Irssi__Irc_dcc_chat_find_id, file, "$");
        (void)newXSproto_portable("Irssi::Irc::dcc_chat_send", XS_Irssi__Irc_dcc_chat_send, file, "$$");
        (void)newXSproto_portable("Irssi::Irc::dcc_ctcp_message", XS_Irssi__Irc_dcc_ctcp_message, file, "$$$$$");
        (void)newXSproto_portable("Irssi::Irc::dcc_get_download_path", XS_Irssi__Irc_dcc_get_download_path, file, "$");
        (void)newXSproto_portable("Irssi::Irc::Dcc::init_rec", XS_Irssi__Irc__Dcc_init_rec, file, "$$$$$");
        (void)newXSproto_portable("Irssi::Irc::Dcc::destroy", XS_Irssi__Irc__Dcc_destroy, file, "$");
        (void)newXSproto_portable("Irssi::Irc::Dcc::close", XS_Irssi__Irc__Dcc_close, file, "$");
        (void)newXSproto_portable("Irssi::Irc::Dcc::reject", XS_Irssi__Irc__Dcc_reject, file, "$$");
        (void)newXSproto_portable("Irssi::Windowitem::get_dcc", XS_Irssi__Windowitem_get_dcc, file, "$");
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

