/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2210 from the
 * contents of Modes.xs. Do not edit this file, edit Modes.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Modes.xs"
#include "module.h"

#line 13 "Modes.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 65 "Modes.c"

XS(XS_Irssi__Irc_modes_join); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc_modes_join)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 4)
       croak_xs_usage(cv,  "server, old, mode, channel");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	Irssi__Irc__Server	server = irssi_ref_object(ST(0));
	char *	old = (char *)SvPV_nolen(ST(1));
	char *	mode = (char *)SvPV_nolen(ST(2));
	int	channel = (int)SvIV(ST(3));
#line 13 "Modes.xs"
	char *ret;
#line 86 "Modes.c"
#line 15 "Modes.xs"
	ret = modes_join(server, old, mode, channel);
	XPUSHs(sv_2mortal(new_pv(ret)));
	g_free(ret);
#line 91 "Modes.c"
	PUTBACK;
	return;
    }
}


XS(XS_Irssi__Irc__Channel_ban_get_mask); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc__Channel_ban_get_mask)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       croak_xs_usage(cv,  "channel, nick, ban_type");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	Irssi__Irc__Channel	channel = irssi_ref_object(ST(0));
	char *	nick = (char *)SvPV_nolen(ST(1));
	int	ban_type = (int)SvIV(ST(2));
#line 29 "Modes.xs"
	char *ret;
#line 116 "Modes.c"
#line 31 "Modes.xs"
	ret = ban_get_mask(channel, nick, ban_type);
	XPUSHs(sv_2mortal(new_pv(ret)));
	g_free(ret);
#line 121 "Modes.c"
	PUTBACK;
	return;
    }
}


XS(XS_Irssi__Irc__Channel_banlist_add); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc__Channel_banlist_add)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 4)
       croak_xs_usage(cv,  "channel, ban, nick, time");
    {
	Irssi__Irc__Channel	channel = irssi_ref_object(ST(0));
	char *	ban = (char *)SvPV_nolen(ST(1));
	char *	nick = (char *)SvPV_nolen(ST(2));
	time_t	time = (time_t)SvNV(ST(3));
	Irssi__Irc__Ban	RETVAL;

	RETVAL = banlist_add(channel, ban, nick, time);
	ST(0) = plain_bless(RETVAL, "Irssi::Irc::Ban");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi__Irc__Channel_banlist_remove); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc__Channel_banlist_remove)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       croak_xs_usage(cv,  "channel, ban, nick");
    {
	Irssi__Irc__Channel	channel = irssi_ref_object(ST(0));
	char *	ban = (char *)SvPV_nolen(ST(1));
	char *	nick = (char *)SvPV_nolen(ST(2));

	banlist_remove(channel, ban, nick);
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Irssi__Irc__Modes); /* prototype to pass -Wmissing-prototypes */
XS(boot_Irssi__Irc__Modes)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK ;

        (void)newXSproto_portable("Irssi::Irc::modes_join", XS_Irssi__Irc_modes_join, file, "$$$$");
        (void)newXSproto_portable("Irssi::Irc::Channel::ban_get_mask", XS_Irssi__Irc__Channel_ban_get_mask, file, "$$$");
        (void)newXSproto_portable("Irssi::Irc::Channel::banlist_add", XS_Irssi__Irc__Channel_banlist_add, file, "$$$$");
        (void)newXSproto_portable("Irssi::Irc::Channel::banlist_remove", XS_Irssi__Irc__Channel_banlist_remove, file, "$$$");
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

