/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2210 from the
 * contents of Formats.xs. Do not edit this file, edit Formats.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Formats.xs"
#include "module.h"

static int magic_free_text_dest(pTHX_ SV *sv, MAGIC *mg)
{
	TEXT_DEST_REC *dest = (TEXT_DEST_REC *) mg->mg_ptr;
	char *target = (char *) dest->target;
	g_free(target);
	g_free(dest);
	mg->mg_ptr = NULL;
	sv_setiv(sv, 0);
	return 0;
}

static MGVTBL vtbl_free_text_dest =
{
    NULL, NULL, NULL, NULL, magic_free_text_dest
};

static SV *perl_format_create_dest(SERVER_REC *server, char *target,
				   int level, WINDOW_REC *window)
{
	TEXT_DEST_REC *dest;
	SV *sv, *ret_sv;

	dest = g_new0(TEXT_DEST_REC, 1);
	format_create_dest(dest, server, g_strdup(target), level, window);

	ret_sv = plain_bless(dest, "Irssi::UI::TextDest");

	sv = *hv_fetch(hvref(ret_sv), "_irssi", 6, 0);
	sv_magic(sv, NULL, '~', NULL, 0);

	SvMAGIC(sv)->mg_private = 0x1551; /* HF */
	SvMAGIC(sv)->mg_virtual = &vtbl_free_text_dest;
	SvMAGIC(sv)->mg_ptr = (char *) dest;

	return ret_sv;
}

#line 50 "Formats.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 102 "Formats.c"

XS(XS_Irssi_format_get_length); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_format_get_length)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "str");
    {
	char *	str = (char *)SvPV_nolen(ST(0));
	int	RETVAL;
	dXSTARG;

	RETVAL = format_get_length(str);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_format_real_length); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_format_real_length)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "str, len");
    {
	char *	str = (char *)SvPV_nolen(ST(0));
	int	len = (int)SvIV(ST(1));
	int	RETVAL;
	dXSTARG;

	RETVAL = format_real_length(str, len);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_strip_codes); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_strip_codes)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "input");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	char *	input = (char *)SvPV_nolen(ST(0));
#line 56 "Formats.xs"
	char *ret;
#line 165 "Formats.c"
#line 58 "Formats.xs"
	ret = strip_codes(input);
	XPUSHs(sv_2mortal(new_pv(ret)));
	g_free(ret);
#line 170 "Formats.c"
	PUTBACK;
	return;
    }
}


XS(XS_Irssi_format_create_dest); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_format_create_dest)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 1 || items > 3)
       croak_xs_usage(cv,  "target, level=MSGLEVEL_CLIENTNOTICE, window=NULL");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	char *	target = (char *)SvPV_nolen(ST(0));
	int	level;
	Irssi__UI__Window	window;

	if (items < 2)
	    level = MSGLEVEL_CLIENTNOTICE;
	else {
	    level = (int)SvIV(ST(1));
	}

	if (items < 3)
	    window = NULL;
	else {
	    window = irssi_ref_object(ST(2));
	}
#line 69 "Formats.xs"
	XPUSHs(sv_2mortal(perl_format_create_dest(NULL, target, level, window)));
#line 207 "Formats.c"
	PUTBACK;
	return;
    }
}


XS(XS_Irssi__UI__Window_format_get_text); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI__Window_format_get_text)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 5)
       croak_xs_usage(cv,  "window, module, server, target, formatnum, ...");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	Irssi__UI__Window	window = irssi_ref_object(ST(0));
	char *	module = (char *)SvPV_nolen(ST(1));
	Irssi__Server	server = irssi_ref_object(ST(2));
	char *	target = (char *)SvPV_nolen(ST(3));
	int	formatnum = (int)SvIV(ST(4));
#line 83 "Formats.xs"
	TEXT_DEST_REC dest;
	THEME_REC *theme;
	char **charargs;
	char *ret;
	int n;
#line 238 "Formats.c"
#line 89 "Formats.xs"
	charargs = g_new0(char *, items-5+1);
        for (n = 5; n < items; n++) {
		charargs[n-5] = (char *)SvPV(ST(n), PL_na);
	}

	format_create_dest(&dest, server, target, 0, window);
	theme = window_get_theme(dest.window);

	ret = format_get_text_theme_charargs(theme, module, &dest, formatnum, charargs);
	g_free(charargs);

	XPUSHs(sv_2mortal(new_pv(ret)));
	g_free_not_null(ret);
#line 253 "Formats.c"
	PUTBACK;
	return;
    }
}


XS(XS_Irssi__Window_format_create_dest); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Window_format_create_dest)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 0 || items > 2)
       croak_xs_usage(cv,  "window=NULL, level=MSGLEVEL_CLIENTNOTICE");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	Irssi__UI__Window	window;
	int	level;

	if (items < 1)
	    window = NULL;
	else {
	    window = irssi_ref_object(ST(0));
	}

	if (items < 2)
	    level = MSGLEVEL_CLIENTNOTICE;
	else {
	    level = (int)SvIV(ST(1));
	}
#line 112 "Formats.xs"
	XPUSHs(sv_2mortal(perl_format_create_dest(NULL, NULL, level, window)));
#line 289 "Formats.c"
	PUTBACK;
	return;
    }
}


XS(XS_Irssi__Server_format_create_dest); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Server_format_create_dest)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 1 || items > 4)
       croak_xs_usage(cv,  "server, target=NULL, level=MSGLEVEL_CLIENTNOTICE, window=NULL");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	Irssi__Server	server = irssi_ref_object(ST(0));
	char *	target;
	int	level;
	Irssi__UI__Window	window;

	if (items < 2)
	    target = NULL;
	else {
	    target = (char *)SvPV_nolen(ST(1));
	}

	if (items < 3)
	    level = MSGLEVEL_CLIENTNOTICE;
	else {
	    level = (int)SvIV(ST(2));
	}

	if (items < 4)
	    window = NULL;
	else {
	    window = irssi_ref_object(ST(3));
	}
#line 125 "Formats.xs"
	XPUSHs(sv_2mortal(perl_format_create_dest(server, target, level, window)));
#line 333 "Formats.c"
	PUTBACK;
	return;
    }
}


XS(XS_Irssi__UI__TextDest_print); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI__TextDest_print)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "dest, str");
    {
	Irssi__UI__TextDest	dest = irssi_ref_object(ST(0));
	char *	str = (char *)SvPV_nolen(ST(1));
#line 136 "Formats.xs"
	printtext_dest(dest, "%s", str);
#line 355 "Formats.c"
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Irssi__UI__Formats); /* prototype to pass -Wmissing-prototypes */
XS(boot_Irssi__UI__Formats)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK ;

        (void)newXSproto_portable("Irssi::format_get_length", XS_Irssi_format_get_length, file, "$");
        (void)newXSproto_portable("Irssi::format_real_length", XS_Irssi_format_real_length, file, "$$");
        (void)newXSproto_portable("Irssi::strip_codes", XS_Irssi_strip_codes, file, "$");
        (void)newXSproto_portable("Irssi::format_create_dest", XS_Irssi_format_create_dest, file, "$;$$");
        (void)newXSproto_portable("Irssi::UI::Window::format_get_text", XS_Irssi__UI__Window_format_get_text, file, "$$$$$;@");
        (void)newXSproto_portable("Irssi::Window::format_create_dest", XS_Irssi__Window_format_create_dest, file, ";$$");
        (void)newXSproto_portable("Irssi::Server::format_create_dest", XS_Irssi__Server_format_create_dest, file, "$;$$$");
        (void)newXSproto_portable("Irssi::UI::TextDest::print", XS_Irssi__UI__TextDest_print, file, "$$");
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

