/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2210 from the
 * contents of UI.xs. Do not edit this file, edit UI.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "UI.xs"
#include "module.h"

void perl_themes_init(void);
void perl_themes_deinit(void);

static int initialized = FALSE;

static void perl_process_fill_hash(HV *hv, PROCESS_REC *process)
{
	hv_store(hv, "id", 2, newSViv(process->id), 0);
	hv_store(hv, "name", 4, new_pv(process->name), 0);
	hv_store(hv, "args", 4, new_pv(process->args), 0);

	hv_store(hv, "pid", 3, newSViv(process->pid), 0);
	hv_store(hv, "target", 6, new_pv(process->target), 0);
	if (process->target_win != NULL) {
		hv_store(hv, "target_win", 10,
			 plain_bless(process->target_win, "Irssi::UI::Window"), 0);
	}
	hv_store(hv, "shell", 5, newSViv(process->shell), 0);
	hv_store(hv, "notice", 6, newSViv(process->notice), 0);
	hv_store(hv, "silent", 6, newSViv(process->silent), 0);
}

static void perl_window_fill_hash(HV *hv, WINDOW_REC *window)
{
	hv_store(hv, "refnum", 6, newSViv(window->refnum), 0);
	hv_store(hv, "name", 4, new_pv(window->name), 0);
	hv_store(hv, "history_name", 12, new_pv(window->history_name), 0);

	hv_store(hv, "width", 5, newSViv(window->width), 0);
	hv_store(hv, "height", 6, newSViv(window->height), 0);

	if (window->active)
		hv_store(hv, "active", 6, iobject_bless(window->active), 0);
	if (window->active_server)
		hv_store(hv, "active_server", 13, iobject_bless(window->active_server), 0);

	hv_store(hv, "servertag", 9, new_pv(window->servertag), 0);
	hv_store(hv, "level", 5, newSViv(window->level), 0);

	hv_store(hv, "immortal", 8, newSViv(window->immortal), 0);
	hv_store(hv, "sticky_refnum", 13, newSViv(window->sticky_refnum), 0);

	hv_store(hv, "data_level", 10, newSViv(window->data_level), 0);
	hv_store(hv, "hilight_color", 13, new_pv(window->hilight_color), 0);

	hv_store(hv, "last_timestamp", 14, newSViv(window->last_timestamp), 0);
	hv_store(hv, "last_line", 9, newSViv(window->last_line), 0);

	hv_store(hv, "theme", 5, plain_bless(window->theme, "Irssi::UI::Theme"), 0);
	hv_store(hv, "theme_name", 10, new_pv(window->theme_name), 0);
}

static void perl_text_dest_fill_hash(HV *hv, TEXT_DEST_REC *dest)
{
	hv_store(hv, "window", 6, plain_bless(dest->window, "Irssi::UI::Window"), 0);
	hv_store(hv, "server", 6, iobject_bless(dest->server), 0);
	hv_store(hv, "target", 6, new_pv(dest->target), 0);
	hv_store(hv, "level", 5, newSViv(dest->level), 0);

	hv_store(hv, "hilight_priority", 16, newSViv(dest->hilight_priority), 0);
	hv_store(hv, "hilight_color", 13, new_pv(dest->hilight_color), 0);
}

static PLAIN_OBJECT_INIT_REC fe_plains[] = {
	{ "Irssi::UI::Process", (PERL_OBJECT_FUNC) perl_process_fill_hash },
	{ "Irssi::UI::Window", (PERL_OBJECT_FUNC) perl_window_fill_hash },
	{ "Irssi::UI::TextDest", (PERL_OBJECT_FUNC) perl_text_dest_fill_hash },

	{ NULL, NULL }
};

#line 84 "UI.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 136 "UI.c"

XS(XS_Irssi__UI_processes); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI_processes)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 81 "UI.xs"
	GSList *tmp;
#line 153 "UI.c"
#line 83 "UI.xs"
	for (tmp = processes; tmp != NULL; tmp = tmp->next) {
		XPUSHs(sv_2mortal(plain_bless(tmp->data, "Irssi::UI::Process")));
	}
#line 158 "UI.c"
	PUTBACK;
	return;
    }
}


XS(XS_Irssi__UI_init); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI_init)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
#line 91 "UI.xs"
	if (initialized) return;
	perl_api_version_check("Irssi::UI");
	initialized = TRUE;

        irssi_add_plains(fe_plains);
        perl_themes_init();
#line 183 "UI.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__UI_deinit); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI_deinit)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
#line 101 "UI.xs"
	if (!initialized) return;
        perl_themes_deinit();
	initialized = FALSE;
#line 204 "UI.c"
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Irssi__UI); /* prototype to pass -Wmissing-prototypes */
XS(boot_Irssi__UI)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK ;

        (void)newXSproto_portable("Irssi::UI::processes", XS_Irssi__UI_processes, file, "");
        (void)newXSproto_portable("Irssi::UI::init", XS_Irssi__UI_init, file, "");
        (void)newXSproto_portable("Irssi::UI::deinit", XS_Irssi__UI_deinit, file, "");

    /* Initialisation Section */

#line 106 "UI.xs"
	irssi_boot(UI__Formats);
	irssi_boot(UI__Themes);
	irssi_boot(UI__Window);

#line 244 "UI.c"

    /* End of Initialisation Section */

#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

