/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2210 from the
 * contents of Window.xs. Do not edit this file, edit Window.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Window.xs"
#include "module.h"

#include "window-activity.h"

#line 15 "Window.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 67 "Window.c"

XS(XS_Irssi_windows); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_windows)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 11 "Window.xs"
	GSList *tmp;
#line 84 "Window.c"
#line 13 "Window.xs"
	for (tmp = windows; tmp != NULL; tmp = tmp->next) {
		XPUSHs(sv_2mortal(plain_bless(tmp->data, "Irssi::UI::Window")));
	}
#line 89 "Window.c"
	PUTBACK;
	return;
    }
}


XS(XS_Irssi_active_win); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_active_win)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	Irssi__UI__Window	RETVAL;
#line 21 "Window.xs"
	RETVAL = active_win;
#line 110 "Window.c"
	ST(0) = plain_bless(RETVAL, "Irssi::UI::Window");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi_active_server); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_active_server)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	Irssi__Server	RETVAL;
#line 28 "Window.xs"
	RETVAL = active_win->active_server;
#line 133 "Window.c"
	ST(0) = iobject_bless((SERVER_REC *)RETVAL);

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi_print); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_print)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 1 || items > 2)
       croak_xs_usage(cv,  "str, level=MSGLEVEL_CLIENTNOTICE");
    {
	char *	str = (char *)SvPV_nolen(ST(0));
	int	level;

	if (items < 2)
	    level = MSGLEVEL_CLIENTNOTICE;
	else {
	    level = (int)SvIV(ST(1));
	}
#line 37 "Window.xs"
	printtext_string(NULL, NULL, level, str);
#line 163 "Window.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi_window_find_name); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_window_find_name)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "name");
    {
	char *	name = (char *)SvPV_nolen(ST(0));
	Irssi__UI__Window	RETVAL;

	RETVAL = window_find_name(name);
	ST(0) = plain_bless(RETVAL, "Irssi::UI::Window");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi_window_find_refnum); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_window_find_refnum)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "refnum");
    {
	int	refnum = (int)SvIV(ST(0));
	Irssi__UI__Window	RETVAL;

	RETVAL = window_find_refnum(refnum);
	ST(0) = plain_bless(RETVAL, "Irssi::UI::Window");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi_window_refnum_prev); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_window_refnum_prev)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "refnum, wrap");
    {
	int	refnum = (int)SvIV(ST(0));
	int	wrap = (int)SvIV(ST(1));
	int	RETVAL;
	dXSTARG;

	RETVAL = window_refnum_prev(refnum, wrap);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_window_refnum_next); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_window_refnum_next)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "refnum, wrap");
    {
	int	refnum = (int)SvIV(ST(0));
	int	wrap = (int)SvIV(ST(1));
	int	RETVAL;
	dXSTARG;

	RETVAL = window_refnum_next(refnum, wrap);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_windows_refnum_last); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_windows_refnum_last)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;

	RETVAL = windows_refnum_last();
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_window_find_level); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_window_find_level)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "level");
    {
	int	level = (int)SvIV(ST(0));
	Irssi__UI__Window	RETVAL;
#line 64 "Window.xs"
	RETVAL = window_find_level(NULL, level);
#line 297 "Window.c"
	ST(0) = plain_bless(RETVAL, "Irssi::UI::Window");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi_window_find_item); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_window_find_item)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "name");
    {
	char *	name = (char *)SvPV_nolen(ST(0));
	Irssi__UI__Window	RETVAL;
#line 72 "Window.xs"
	RETVAL = window_find_item(NULL, name);
#line 321 "Window.c"
	ST(0) = plain_bless(RETVAL, "Irssi::UI::Window");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi_window_find_closest); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_window_find_closest)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "name, level");
    {
	char *	name = (char *)SvPV_nolen(ST(0));
	int	level = (int)SvIV(ST(1));
	Irssi__UI__Window	RETVAL;
#line 81 "Window.xs"
	RETVAL = window_find_closest(NULL, name, level);
#line 346 "Window.c"
	ST(0) = plain_bless(RETVAL, "Irssi::UI::Window");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi_window_item_find); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_window_item_find)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "name");
    {
	char *	name = (char *)SvPV_nolen(ST(0));
	Irssi__Windowitem	RETVAL;
#line 89 "Window.xs"
	RETVAL = window_item_find(NULL, name);
#line 370 "Window.c"
	ST(0) = iobject_bless((SERVER_REC *)RETVAL);

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi__Server_print); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Server_print)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 3 || items > 4)
       croak_xs_usage(cv,  "server, channel, str, level=MSGLEVEL_CLIENTNOTICE");
    {
	Irssi__Server	server = irssi_ref_object(ST(0));
	char *	channel = (char *)SvPV_nolen(ST(1));
	char *	str = (char *)SvPV_nolen(ST(2));
	int	level;

	if (items < 4)
	    level = MSGLEVEL_CLIENTNOTICE;
	else {
	    level = (int)SvIV(ST(3));
	}
#line 105 "Window.xs"
	printtext_string(server, channel, level, str);
#line 402 "Window.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Server_window_item_find); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Server_window_item_find)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "server, name");
    {
	Irssi__Server	server = irssi_ref_object(ST(0));
	char *	name = (char *)SvPV_nolen(ST(1));
	Irssi__Windowitem	RETVAL;

	RETVAL = window_item_find(server, name);
	ST(0) = iobject_bless((SERVER_REC *)RETVAL);

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi__Server_window_find_item); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Server_window_find_item)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "server, name");
    {
	Irssi__Server	server = irssi_ref_object(ST(0));
	char *	name = (char *)SvPV_nolen(ST(1));
	Irssi__UI__Window	RETVAL;

	RETVAL = window_find_item(server, name);
	ST(0) = plain_bless(RETVAL, "Irssi::UI::Window");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi__Server_window_find_level); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Server_window_find_level)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "server, level");
    {
	Irssi__Server	server = irssi_ref_object(ST(0));
	int	level = (int)SvIV(ST(1));
	Irssi__UI__Window	RETVAL;

	RETVAL = window_find_level(server, level);
	ST(0) = plain_bless(RETVAL, "Irssi::UI::Window");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi__Server_window_find_closest); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Server_window_find_closest)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       croak_xs_usage(cv,  "server, name, level");
    {
	Irssi__Server	server = irssi_ref_object(ST(0));
	char *	name = (char *)SvPV_nolen(ST(1));
	int	level = (int)SvIV(ST(2));
	Irssi__UI__Window	RETVAL;

	RETVAL = window_find_closest(server, name, level);
	ST(0) = plain_bless(RETVAL, "Irssi::UI::Window");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi__UI__Window_items); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI__Window_items)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "window");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	Irssi__UI__Window	window = irssi_ref_object(ST(0));
#line 137 "Window.xs"
	GSList *tmp;
#line 521 "Window.c"
#line 139 "Window.xs"
	for (tmp = window->items; tmp != NULL; tmp = tmp->next) {
                CHANNEL_REC *rec = tmp->data;

		XPUSHs(sv_2mortal(iobject_bless(rec)));
	}
#line 528 "Window.c"
	PUTBACK;
	return;
    }
}


XS(XS_Irssi__UI__Window_print); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI__Window_print)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 2 || items > 3)
       croak_xs_usage(cv,  "window, str, level=MSGLEVEL_CLIENTNOTICE");
    {
	Irssi__UI__Window	window = irssi_ref_object(ST(0));
	char *	str = (char *)SvPV_nolen(ST(1));
	int	level;

	if (items < 3)
	    level = MSGLEVEL_CLIENTNOTICE;
	else {
	    level = (int)SvIV(ST(2));
	}
#line 151 "Window.xs"
	printtext_string_window(window, level, str);
#line 557 "Window.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__UI__Window_command); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI__Window_command)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "window, cmd");
    {
	Irssi__UI__Window	window = irssi_ref_object(ST(0));
	char *	cmd = (char *)SvPV_nolen(ST(1));
#line 158 "Window.xs"
	WINDOW_REC *old;
#line 578 "Window.c"
#line 160 "Window.xs"
	old = active_win;
	active_win = window;
	perl_command(cmd, window->active_server, window->active);
	if (active_win == window &&
	    g_slist_find(windows, old) != NULL)
        	active_win = old;
#line 586 "Window.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__UI__Window_item_add); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI__Window_item_add)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       croak_xs_usage(cv,  "window, item, automatic");
    {
	Irssi__UI__Window	window = irssi_ref_object(ST(0));
	Irssi__Windowitem	item = irssi_ref_object(ST(1));
	int	automatic = (int)SvIV(ST(2));

	window_item_add(window, item, automatic);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__UI__Window_item_remove); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI__Window_item_remove)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "item");
    {
	Irssi__Windowitem	item = irssi_ref_object(ST(0));

	window_item_remove(item);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__UI__Window_item_destroy); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI__Window_item_destroy)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "item");
    {
	Irssi__Windowitem	item = irssi_ref_object(ST(0));

	window_item_destroy(item);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__UI__Window_item_prev); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI__Window_item_prev)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "window");
    {
	Irssi__UI__Window	window = irssi_ref_object(ST(0));

	window_item_prev(window);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__UI__Window_item_next); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI__Window_item_next)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "window");
    {
	Irssi__UI__Window	window = irssi_ref_object(ST(0));

	window_item_next(window);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__UI__Window_destroy); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI__Window_destroy)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "window");
    {
	Irssi__UI__Window	window = irssi_ref_object(ST(0));

	window_destroy(window);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__UI__Window_set_active); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI__Window_set_active)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "window");
    {
	Irssi__UI__Window	window = irssi_ref_object(ST(0));

	window_set_active(window);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__UI__Window_change_server); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI__Window_change_server)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "window, server");
    {
	Irssi__UI__Window	window = irssi_ref_object(ST(0));
	Irssi__Server	server = irssi_ref_object(ST(1));

	window_change_server(window, server);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__UI__Window_set_refnum); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI__Window_set_refnum)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "window, refnum");
    {
	Irssi__UI__Window	window = irssi_ref_object(ST(0));
	int	refnum = (int)SvIV(ST(1));

	window_set_refnum(window, refnum);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__UI__Window_set_name); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI__Window_set_name)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "window, name");
    {
	Irssi__UI__Window	window = irssi_ref_object(ST(0));
	char *	name = (char *)SvPV_nolen(ST(1));

	window_set_name(window, name);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__UI__Window_set_history); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI__Window_set_history)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "window, name");
    {
	Irssi__UI__Window	window = irssi_ref_object(ST(0));
	char *	name = (char *)SvPV_nolen(ST(1));

	window_set_history(window, name);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__UI__Window_set_level); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI__Window_set_level)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "window, level");
    {
	Irssi__UI__Window	window = irssi_ref_object(ST(0));
	int	level = (int)SvIV(ST(1));

	window_set_level(window, level);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__UI__Window_activity); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI__Window_activity)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 2 || items > 3)
       croak_xs_usage(cv,  "window, data_level, hilight_color=NULL");
    {
	Irssi__UI__Window	window = irssi_ref_object(ST(0));
	int	data_level = (int)SvIV(ST(1));
	char *	hilight_color;

	if (items < 3)
	    hilight_color = NULL;
	else {
	    hilight_color = (char *)SvPV_nolen(ST(2));
	}

	window_activity(window, data_level, hilight_color);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__UI__Window_get_active_name); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI__Window_get_active_name)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "window");
    {
	Irssi__UI__Window	window = irssi_ref_object(ST(0));
	char *	RETVAL;
	dXSTARG;
#line 232 "Window.xs"
	RETVAL = (char *) window_get_active_name(window);
#line 870 "Window.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Irssi__UI__Window_item_find); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI__Window_item_find)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       croak_xs_usage(cv,  "window, server, name");
    {
	Irssi__UI__Window	window = irssi_ref_object(ST(0));
	Irssi__Server	server = irssi_ref_object(ST(1));
	char *	name = (char *)SvPV_nolen(ST(2));
	Irssi__Windowitem	RETVAL;
#line 242 "Window.xs"
	RETVAL = window_item_find_window(window, server, name);
#line 894 "Window.c"
	ST(0) = iobject_bless((SERVER_REC *)RETVAL);

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi__UI__Window_get_history_lines); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI__Window_get_history_lines)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "window");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	Irssi__UI__Window	window = irssi_ref_object(ST(0));
#line 250 "Window.xs"
	HISTORY_REC *rec;
	GList *tmp;
#line 920 "Window.c"
#line 253 "Window.xs"
	rec = command_history_current(window);
	for (tmp = rec->list; tmp != NULL; tmp = tmp->next)
		XPUSHs(sv_2mortal(new_pv(tmp->data)));
#line 925 "Window.c"
	PUTBACK;
	return;
    }
}


XS(XS_Irssi__Windowitem_print); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Windowitem_print)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 2 || items > 3)
       croak_xs_usage(cv,  "item, str, level=MSGLEVEL_CLIENTNOTICE");
    {
	Irssi__Windowitem	item = irssi_ref_object(ST(0));
	int	level;
	char *	str = (char *)SvPV_nolen(ST(1));

	if (items < 3)
	    level = MSGLEVEL_CLIENTNOTICE;
	else {
	    level = (int)SvIV(ST(2));
	}
#line 267 "Window.xs"
	printtext_string(item->server, item->visible_name, level, str);
#line 954 "Window.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Windowitem_window_create); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Windowitem_window_create)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "item, automatic");
    {
	Irssi__Windowitem	item = irssi_ref_object(ST(0));
	int	automatic = (int)SvIV(ST(1));
	Irssi__UI__Window	RETVAL;

	RETVAL = window_create(item, automatic);
	ST(0) = plain_bless(RETVAL, "Irssi::UI::Window");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi__Windowitem_window); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Windowitem_window)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "item");
    {
	Irssi__Windowitem	item = irssi_ref_object(ST(0));
	Irssi__UI__Window	RETVAL;
#line 278 "Window.xs"
	RETVAL = window_item_window(item);
#line 999 "Window.c"
	ST(0) = plain_bless(RETVAL, "Irssi::UI::Window");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi__Windowitem_change_server); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Windowitem_change_server)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "item, server");
    {
	Irssi__Windowitem	item = irssi_ref_object(ST(0));
	Irssi__Server	server = irssi_ref_object(ST(1));

	window_item_change_server(item, server);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Windowitem_is_active); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Windowitem_is_active)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "item");
    {
	Irssi__Windowitem	item = irssi_ref_object(ST(0));
	int	RETVAL;
	dXSTARG;

	RETVAL = window_item_is_active(item);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi__Windowitem_set_active); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Windowitem_set_active)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "item");
    {
	Irssi__Windowitem	item = irssi_ref_object(ST(0));
#line 295 "Window.xs"
	window_item_set_active(window_item_window(item), item);
#line 1064 "Window.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Windowitem_activity); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Windowitem_activity)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 2 || items > 3)
       croak_xs_usage(cv,  "item, data_level, hilight_color=NULL");
    {
	Irssi__Windowitem	item = irssi_ref_object(ST(0));
	int	data_level = (int)SvIV(ST(1));
	char *	hilight_color;

	if (items < 3)
	    hilight_color = NULL;
	else {
	    hilight_color = (char *)SvPV_nolen(ST(2));
	}

	window_item_activity(item, data_level, hilight_color);
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Irssi__UI__Window); /* prototype to pass -Wmissing-prototypes */
XS(boot_Irssi__UI__Window)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK ;

        (void)newXSproto_portable("Irssi::windows", XS_Irssi_windows, file, "");
        (void)newXSproto_portable("Irssi::active_win", XS_Irssi_active_win, file, "");
        (void)newXSproto_portable("Irssi::active_server", XS_Irssi_active_server, file, "");
        (void)newXSproto_portable("Irssi::print", XS_Irssi_print, file, "$;$");
        (void)newXSproto_portable("Irssi::window_find_name", XS_Irssi_window_find_name, file, "$");
        (void)newXSproto_portable("Irssi::window_find_refnum", XS_Irssi_window_find_refnum, file, "$");
        (void)newXSproto_portable("Irssi::window_refnum_prev", XS_Irssi_window_refnum_prev, file, "$$");
        (void)newXSproto_portable("Irssi::window_refnum_next", XS_Irssi_window_refnum_next, file, "$$");
        (void)newXSproto_portable("Irssi::windows_refnum_last", XS_Irssi_windows_refnum_last, file, "");
        (void)newXSproto_portable("Irssi::window_find_level", XS_Irssi_window_find_level, file, "$");
        (void)newXSproto_portable("Irssi::window_find_item", XS_Irssi_window_find_item, file, "$");
        (void)newXSproto_portable("Irssi::window_find_closest", XS_Irssi_window_find_closest, file, "$$");
        (void)newXSproto_portable("Irssi::window_item_find", XS_Irssi_window_item_find, file, "$");
        (void)newXSproto_portable("Irssi::Server::print", XS_Irssi__Server_print, file, "$$$;$");
        (void)newXSproto_portable("Irssi::Server::window_item_find", XS_Irssi__Server_window_item_find, file, "$$");
        (void)newXSproto_portable("Irssi::Server::window_find_item", XS_Irssi__Server_window_find_item, file, "$$");
        (void)newXSproto_portable("Irssi::Server::window_find_level", XS_Irssi__Server_window_find_level, file, "$$");
        (void)newXSproto_portable("Irssi::Server::window_find_closest", XS_Irssi__Server_window_find_closest, file, "$$$");
        (void)newXSproto_portable("Irssi::UI::Window::items", XS_Irssi__UI__Window_items, file, "$");
        (void)newXSproto_portable("Irssi::UI::Window::print", XS_Irssi__UI__Window_print, file, "$$;$");
        (void)newXSproto_portable("Irssi::UI::Window::command", XS_Irssi__UI__Window_command, file, "$$");
        (void)newXSproto_portable("Irssi::UI::Window::item_add", XS_Irssi__UI__Window_item_add, file, "$$$");
        (void)newXSproto_portable("Irssi::UI::Window::item_remove", XS_Irssi__UI__Window_item_remove, file, "$");
        (void)newXSproto_portable("Irssi::UI::Window::item_destroy", XS_Irssi__UI__Window_item_destroy, file, "$");
        (void)newXSproto_portable("Irssi::UI::Window::item_prev", XS_Irssi__UI__Window_item_prev, file, "$");
        (void)newXSproto_portable("Irssi::UI::Window::item_next", XS_Irssi__UI__Window_item_next, file, "$");
        (void)newXSproto_portable("Irssi::UI::Window::destroy", XS_Irssi__UI__Window_destroy, file, "$");
        (void)newXSproto_portable("Irssi::UI::Window::set_active", XS_Irssi__UI__Window_set_active, file, "$");
        (void)newXSproto_portable("Irssi::UI::Window::change_server", XS_Irssi__UI__Window_change_server, file, "$$");
        (void)newXSproto_portable("Irssi::UI::Window::set_refnum", XS_Irssi__UI__Window_set_refnum, file, "$$");
        (void)newXSproto_portable("Irssi::UI::Window::set_name", XS_Irssi__UI__Window_set_name, file, "$$");
        (void)newXSproto_portable("Irssi::UI::Window::set_history", XS_Irssi__UI__Window_set_history, file, "$$");
        (void)newXSproto_portable("Irssi::UI::Window::set_level", XS_Irssi__UI__Window_set_level, file, "$$");
        (void)newXSproto_portable("Irssi::UI::Window::activity", XS_Irssi__UI__Window_activity, file, "$$;$");
        (void)newXSproto_portable("Irssi::UI::Window::get_active_name", XS_Irssi__UI__Window_get_active_name, file, "$");
        (void)newXSproto_portable("Irssi::UI::Window::item_find", XS_Irssi__UI__Window_item_find, file, "$$$");
        (void)newXSproto_portable("Irssi::UI::Window::get_history_lines", XS_Irssi__UI__Window_get_history_lines, file, "$");
        (void)newXSproto_portable("Irssi::Windowitem::print", XS_Irssi__Windowitem_print, file, "$$;$");
        (void)newXSproto_portable("Irssi::Windowitem::window_create", XS_Irssi__Windowitem_window_create, file, "$$");
        (void)newXSproto_portable("Irssi::Windowitem::window", XS_Irssi__Windowitem_window, file, "$");
        (void)newXSproto_portable("Irssi::Windowitem::change_server", XS_Irssi__Windowitem_change_server, file, "$$");
        (void)newXSproto_portable("Irssi::Windowitem::is_active", XS_Irssi__Windowitem_is_active, file, "$");
        (void)newXSproto_portable("Irssi::Windowitem::set_active", XS_Irssi__Windowitem_set_active, file, "$");
        (void)newXSproto_portable("Irssi::Windowitem::activity", XS_Irssi__Windowitem_activity, file, "$$;$");
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

