/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2210 from the
 * contents of Core.xs. Do not edit this file, edit Core.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Core.xs"
#include "module.h"
#include "irssi-version.h"
#include "core.h"

#include "pidwait.h"
#include "session.h"

#define DEFAULT_COMMAND_CATEGORY "Perl scripts' commands"

static void perl_signal_add_hash(int priority, SV *sv)
{
	HV *hv;
        HE *he;
	I32 len;

	if (!is_hvref(sv))
		croak("Usage: Irssi::signal_add(hash)");

        hv = hvref(sv);
	hv_iterinit(hv);
	while ((he = hv_iternext(hv)) != NULL)
                perl_signal_add_full(hv_iterkey(he, &len), HeVAL(he), priority);
}

static void perl_command_bind_add_hash(int priority, SV *sv, char *category)
{
	HV *hv;
        HE *he;
	I32 len;

        hv = hvref(sv);
	hv_iterinit(hv);
	while ((he = hv_iternext(hv)) != NULL)
		perl_command_bind_to(hv_iterkey(he, &len), category, HeVAL(he), priority);
}

static void handle_command_bind(int priority, int items, SV *p0, SV *p1, SV *p2)
{
	char *category;
	int hash;

	hash = items > 0 && is_hvref(p0);
	if (!hash) {
		if (items < 2 || items > 3)
			croak("Usage: Irssi::command_bind(signal, func, category)");
	} else if (items > 2)
		croak("Usage: Irssi::command_bind(signals_hash, category)");

	if (!hash) {
		category = items < 3 ? DEFAULT_COMMAND_CATEGORY :
			(char *)SvPV(p2, PL_na);
		perl_command_bind_to((char *)SvPV(p0, PL_na), category, p1, priority);
	} else {
		category = items < 2 ? DEFAULT_COMMAND_CATEGORY :
			(char *)SvPV(p1, PL_na);
		perl_command_bind_add_hash(priority, p0, category);
	}
}

static void add_tuple(gpointer key_, gpointer value_, gpointer user_data)
{
	HV *hash = user_data;
	char *key = key_;
	char *value = value_;
	hv_store(hash, key, strlen(key), new_pv(value), 0);
}

static void wrap_signal_emit(void *signal, void **p) {
	signal_emit(signal, 6, p[0], p[1], p[2], p[3], p[4], p[5]);
}

static void wrap_signal_continue(void *dummy, void **p) {
	(void)dummy;
	signal_continue(6, p[0], p[1], p[2], p[3], p[4], p[5]);
}

#line 87 "Core.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 139 "Core.c"

XS(XS_Irssi_signal_emit); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_signal_emit)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 1)
       croak_xs_usage(cv,  "signal, ...");
    {
	char *	signal = (char *)SvPV_nolen(ST(0));
#line 84 "Core.xs"
	int signal_id;
	SV *args[SIGNAL_MAX_ARGUMENTS];
	int n, used;

	signal_id = signal_get_uniq_id(signal);
	used = items - 1;
	if (used > SIGNAL_MAX_ARGUMENTS) {
		used = SIGNAL_MAX_ARGUMENTS;
	}
	for (n = 0; n < used; ++n) {
		args[n] = ST(n + 1);
	}
	perl_signal_args_to_c(wrap_signal_emit, signal, signal_id, args, used);
#line 167 "Core.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi_signal_continue); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_signal_continue)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    PERL_UNUSED_VAR(cv); /* -W */
    {
#line 101 "Core.xs"
	SV *args[SIGNAL_MAX_ARGUMENTS];
	int n, used;

	used = items;
	if (used > SIGNAL_MAX_ARGUMENTS) {
		used = SIGNAL_MAX_ARGUMENTS;
	}
	for (n = 0; n < used; ++n) {
		args[n] = ST(n);
	}
	perl_signal_args_to_c(wrap_signal_continue, NULL, signal_get_emitted_id(), args, used);
#line 195 "Core.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi_signal_add); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_signal_add)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    PERL_UNUSED_VAR(cv); /* -W */
    {
#line 116 "Core.xs"
	if (items != 1 && items != 2)
		croak("Usage: Irssi::signal_add(signal, func)");
	if (items == 2)
		perl_signal_add_full((char *)SvPV(ST(0),PL_na), ST(1),
				     SIGNAL_PRIORITY_DEFAULT);
	else
		perl_signal_add_hash(SIGNAL_PRIORITY_DEFAULT, ST(0));
#line 219 "Core.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi_signal_add_first); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_signal_add_first)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    PERL_UNUSED_VAR(cv); /* -W */
    {
#line 127 "Core.xs"
	if (items != 1 && items != 2)
		croak("Usage: Irssi::signal_add_first(signal, func)");
	if (items == 2)
		perl_signal_add_full((char *)SvPV(ST(0),PL_na), ST(1),
				     SIGNAL_PRIORITY_HIGH);
	else
		perl_signal_add_hash(SIGNAL_PRIORITY_HIGH, ST(0));
#line 243 "Core.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi_signal_add_last); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_signal_add_last)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    PERL_UNUSED_VAR(cv); /* -W */
    {
#line 138 "Core.xs"
	if (items != 1 && items != 2)
		croak("Usage: Irssi::signal_add_last(signal, func)");
	if (items == 2)
		perl_signal_add_full((char *)SvPV(ST(0),PL_na), ST(1),
				     SIGNAL_PRIORITY_LOW);
	else
		perl_signal_add_hash(SIGNAL_PRIORITY_LOW, ST(0));
#line 267 "Core.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi_signal_add_priority); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_signal_add_priority)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    PERL_UNUSED_VAR(cv); /* -W */
    {
#line 149 "Core.xs"
	if (items != 2 && items != 3)
		croak("Usage: Irssi::signal_add_priority(signal, func, priority)");
	if (items == 3)
		perl_signal_add_full((char *)SvPV(ST(0),PL_na), ST(1), SvIV(ST(2)));
	else
		perl_signal_add_hash(SvIV(ST(0)), ST(1));
#line 290 "Core.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi_signal_register); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_signal_register)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    PERL_UNUSED_VAR(cv); /* -W */
    {
#line 159 "Core.xs"
	HV *hv;
        HE *he;
	I32 len, pos;
	const char *arr[7];
#line 311 "Core.c"
#line 164 "Core.xs"
	if (items != 1 || !is_hvref(ST(0)))
		croak("Usage: Irssi::signal_register(hash)");

        hv = hvref(ST(0));
	hv_iterinit(hv);
	while ((he = hv_iternext(hv)) != NULL) {
		const char *key = hv_iterkey(he, &len);
		SV *val = HeVAL(he);
		AV *av;

		if (!SvROK(val) || SvTYPE(SvRV(val)) != SVt_PVAV)
			croak("not array reference");

		av = (AV *) SvRV(val);
		len = av_len(av)+1;
		if (len > 6) len = 6;
		for (pos = 0; pos < len; pos++) {
                	SV **val = av_fetch(av, pos, 0);
			arr[pos] = SvPV(*val, PL_na);
		}
		arr[pos] = NULL;
		perl_signal_register(key, arr);
	}
#line 336 "Core.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi_SIGNAL_PRIORITY_LOW); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_SIGNAL_PRIORITY_LOW)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 192 "Core.xs"
	RETVAL = SIGNAL_PRIORITY_LOW;
#line 357 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_SIGNAL_PRIORITY_DEFAULT); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_SIGNAL_PRIORITY_DEFAULT)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 199 "Core.xs"
	RETVAL = SIGNAL_PRIORITY_DEFAULT;
#line 379 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_SIGNAL_PRIORITY_HIGH); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_SIGNAL_PRIORITY_HIGH)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 206 "Core.xs"
	RETVAL = SIGNAL_PRIORITY_HIGH;
#line 401 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_signal_remove); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_signal_remove)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "signal, func");
    {
	char *	signal = (char *)SvPV_nolen(ST(0));
	SV *	func = ST(1);
#line 215 "Core.xs"
	perl_signal_remove(signal, func);
#line 423 "Core.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi_signal_stop); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_signal_stop)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {

	signal_stop();
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi_signal_stop_by_name); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_signal_stop_by_name)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "signal");
    {
	char *	signal = (char *)SvPV_nolen(ST(0));

	signal_stop_by_name(signal);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi_signal_get_emitted); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_signal_get_emitted)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	char *	RETVAL;
	dXSTARG;
#line 227 "Core.xs"
	RETVAL = (char *) signal_get_emitted();
#line 481 "Core.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Irssi_signal_get_emitted_id); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_signal_get_emitted_id)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;

	RETVAL = signal_get_emitted_id();
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_timeout_add); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_timeout_add)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       croak_xs_usage(cv,  "msecs, func, data");
    {
	int	msecs = (int)SvIV(ST(0));
	SV *	func = ST(1);
	SV *	data = ST(2);
	int	RETVAL;
	dXSTARG;
#line 240 "Core.xs"
	if (msecs < 10) {
		croak("Irssi::timeout() : msecs must be >= 10");
		RETVAL = -1;
	} else {
		RETVAL = perl_timeout_add(msecs, func, data, FALSE);
	}
#line 532 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_timeout_add_once); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_timeout_add_once)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       croak_xs_usage(cv,  "msecs, func, data");
    {
	int	msecs = (int)SvIV(ST(0));
	SV *	func = ST(1);
	SV *	data = ST(2);
	int	RETVAL;
	dXSTARG;
#line 255 "Core.xs"
	if (msecs < 10) {
		croak("Irssi::timeout_once() : msecs must be >= 10");
		RETVAL = -1;
	} else {
		RETVAL = perl_timeout_add(msecs, func, data, TRUE);
	}
#line 562 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_timeout_remove); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_timeout_remove)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "tag");
    {
	int	tag = (int)SvIV(ST(0));
#line 268 "Core.xs"
	perl_source_remove(tag);
#line 583 "Core.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi_INPUT_READ); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_INPUT_READ)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 274 "Core.xs"
	RETVAL = G_INPUT_READ;
#line 604 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_INPUT_WRITE); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_INPUT_WRITE)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 281 "Core.xs"
	RETVAL = G_INPUT_WRITE;
#line 626 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_input_add); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_input_add)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 4)
       croak_xs_usage(cv,  "source, condition, func, data");
    {
	int	source = (int)SvIV(ST(0));
	int	condition = (int)SvIV(ST(1));
	SV *	func = ST(2);
	SV *	data = ST(3);
	int	RETVAL;
	dXSTARG;
#line 292 "Core.xs"
	RETVAL = perl_input_add(source, condition, func, data, FALSE);
#line 652 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_input_remove); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_input_remove)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "tag");
    {
	int	tag = (int)SvIV(ST(0));
#line 300 "Core.xs"
	perl_source_remove(tag);
#line 673 "Core.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi_MSGLEVEL_CRAP); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_MSGLEVEL_CRAP)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 306 "Core.xs"
	RETVAL = MSGLEVEL_CRAP;
#line 694 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_MSGLEVEL_MSGS); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_MSGLEVEL_MSGS)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 313 "Core.xs"
	RETVAL = MSGLEVEL_MSGS;
#line 716 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_MSGLEVEL_PUBLIC); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_MSGLEVEL_PUBLIC)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 320 "Core.xs"
	RETVAL = MSGLEVEL_PUBLIC;
#line 738 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_MSGLEVEL_NOTICES); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_MSGLEVEL_NOTICES)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 327 "Core.xs"
	RETVAL = MSGLEVEL_NOTICES;
#line 760 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_MSGLEVEL_SNOTES); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_MSGLEVEL_SNOTES)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 334 "Core.xs"
	RETVAL = MSGLEVEL_SNOTES;
#line 782 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_MSGLEVEL_CTCPS); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_MSGLEVEL_CTCPS)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 341 "Core.xs"
	RETVAL = MSGLEVEL_CTCPS;
#line 804 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_MSGLEVEL_ACTIONS); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_MSGLEVEL_ACTIONS)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 348 "Core.xs"
	RETVAL = MSGLEVEL_ACTIONS;
#line 826 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_MSGLEVEL_JOINS); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_MSGLEVEL_JOINS)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 355 "Core.xs"
	RETVAL = MSGLEVEL_JOINS;
#line 848 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_MSGLEVEL_PARTS); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_MSGLEVEL_PARTS)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 362 "Core.xs"
	RETVAL = MSGLEVEL_PARTS;
#line 870 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_MSGLEVEL_QUITS); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_MSGLEVEL_QUITS)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 369 "Core.xs"
	RETVAL = MSGLEVEL_QUITS;
#line 892 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_MSGLEVEL_KICKS); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_MSGLEVEL_KICKS)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 376 "Core.xs"
	RETVAL = MSGLEVEL_KICKS;
#line 914 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_MSGLEVEL_MODES); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_MSGLEVEL_MODES)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 383 "Core.xs"
	RETVAL = MSGLEVEL_MODES;
#line 936 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_MSGLEVEL_TOPICS); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_MSGLEVEL_TOPICS)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 390 "Core.xs"
	RETVAL = MSGLEVEL_TOPICS;
#line 958 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_MSGLEVEL_WALLOPS); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_MSGLEVEL_WALLOPS)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 397 "Core.xs"
	RETVAL = MSGLEVEL_WALLOPS;
#line 980 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_MSGLEVEL_INVITES); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_MSGLEVEL_INVITES)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 404 "Core.xs"
	RETVAL = MSGLEVEL_INVITES;
#line 1002 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_MSGLEVEL_NICKS); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_MSGLEVEL_NICKS)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 411 "Core.xs"
	RETVAL = MSGLEVEL_NICKS;
#line 1024 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_MSGLEVEL_DCC); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_MSGLEVEL_DCC)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 418 "Core.xs"
	RETVAL = MSGLEVEL_DCC;
#line 1046 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_MSGLEVEL_DCCMSGS); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_MSGLEVEL_DCCMSGS)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 425 "Core.xs"
	RETVAL = MSGLEVEL_DCCMSGS;
#line 1068 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_MSGLEVEL_CLIENTNOTICE); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_MSGLEVEL_CLIENTNOTICE)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 432 "Core.xs"
	RETVAL = MSGLEVEL_CLIENTNOTICE;
#line 1090 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_MSGLEVEL_CLIENTCRAP); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_MSGLEVEL_CLIENTCRAP)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 439 "Core.xs"
	RETVAL = MSGLEVEL_CLIENTCRAP;
#line 1112 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_MSGLEVEL_CLIENTERROR); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_MSGLEVEL_CLIENTERROR)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 446 "Core.xs"
	RETVAL = MSGLEVEL_CLIENTERROR;
#line 1134 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_MSGLEVEL_HILIGHT); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_MSGLEVEL_HILIGHT)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 453 "Core.xs"
	RETVAL = MSGLEVEL_HILIGHT;
#line 1156 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_MSGLEVEL_ALL); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_MSGLEVEL_ALL)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 460 "Core.xs"
	RETVAL = MSGLEVEL_ALL;
#line 1178 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_MSGLEVEL_NOHILIGHT); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_MSGLEVEL_NOHILIGHT)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 467 "Core.xs"
	RETVAL = MSGLEVEL_NOHILIGHT;
#line 1200 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_MSGLEVEL_NO_ACT); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_MSGLEVEL_NO_ACT)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 474 "Core.xs"
	RETVAL = MSGLEVEL_NO_ACT;
#line 1222 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_MSGLEVEL_NEVER); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_MSGLEVEL_NEVER)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 481 "Core.xs"
	RETVAL = MSGLEVEL_NEVER;
#line 1244 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_MSGLEVEL_LASTLOG); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_MSGLEVEL_LASTLOG)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 488 "Core.xs"
	RETVAL = MSGLEVEL_LASTLOG;
#line 1266 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_level2bits); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_level2bits)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "str");
    {
	char *	str = (char *)SvPV_nolen(ST(0));
	int	RETVAL;
	dXSTARG;
#line 496 "Core.xs"
	RETVAL = level2bits(str, NULL);
#line 1289 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_bits2level); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_bits2level)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "bits");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	int	bits = (int)SvIV(ST(0));
#line 504 "Core.xs"
	char *ret;
#line 1312 "Core.c"
#line 506 "Core.xs"
	ret = bits2level(bits);
	XPUSHs(sv_2mortal(new_pv(ret)));
	g_free(ret);
#line 1317 "Core.c"
	PUTBACK;
	return;
    }
}


XS(XS_Irssi_combine_level); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_combine_level)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "level, str");
    {
	int	level = (int)SvIV(ST(0));
	char *	str = (char *)SvPV_nolen(ST(1));
	int	RETVAL;
	dXSTARG;

	RETVAL = combine_level(level, str);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_command); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_command)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "cmd");
    {
	char *	cmd = (char *)SvPV_nolen(ST(0));
#line 519 "Core.xs"
	perl_command(cmd, NULL, NULL);
#line 1361 "Core.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi_commands); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_commands)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 524 "Core.xs"
	GSList *tmp;
#line 1382 "Core.c"
#line 526 "Core.xs"
	for (tmp = commands; tmp != NULL; tmp = tmp->next) {
		XPUSHs(sv_2mortal(plain_bless(tmp->data, "Irssi::Command")));
	}
#line 1387 "Core.c"
	PUTBACK;
	return;
    }
}


XS(XS_Irssi_command_bind_first); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_command_bind_first)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    PERL_UNUSED_VAR(cv); /* -W */
    {
#line 533 "Core.xs"
	handle_command_bind(SIGNAL_PRIORITY_HIGH, items, ST(0), ST(1), ST(2));
#line 1406 "Core.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi_command_bind); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_command_bind)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    PERL_UNUSED_VAR(cv); /* -W */
    {
#line 538 "Core.xs"
	handle_command_bind(SIGNAL_PRIORITY_DEFAULT, items, ST(0), ST(1), ST(2));
#line 1424 "Core.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi_command_bind_last); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_command_bind_last)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    PERL_UNUSED_VAR(cv); /* -W */
    {
#line 543 "Core.xs"
	handle_command_bind(SIGNAL_PRIORITY_LOW, items, ST(0), ST(1), ST(2));
#line 1442 "Core.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi_command_runsub); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_command_runsub)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 4)
       croak_xs_usage(cv,  "cmd, data, server, item");
    {
	char *	cmd = (char *)SvPV_nolen(ST(0));
	char *	data = (char *)SvPV_nolen(ST(1));
	Irssi__Server	server = irssi_ref_object(ST(2));
	Irssi__Windowitem	item = irssi_ref_object(ST(3));
#line 552 "Core.xs"
	perl_command_runsub(cmd, data, server, item);
#line 1465 "Core.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi_command_unbind); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_command_unbind)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "cmd, func");
    {
	char *	cmd = (char *)SvPV_nolen(ST(0));
	SV *	func = ST(1);
#line 559 "Core.xs"
	perl_command_unbind(cmd, func);
#line 1486 "Core.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi_command_set_options); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_command_set_options)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "cmd, options");
    {
	char *	cmd = (char *)SvPV_nolen(ST(0));
	char *	options = (char *)SvPV_nolen(ST(1));

	command_set_options(cmd, options);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi_command_parse_options); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_command_parse_options)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "cmd, data");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	char *	cmd = (char *)SvPV_nolen(ST(0));
	char *	data = (char *)SvPV_nolen(ST(1));
#line 571 "Core.xs"
	HV *hash;
	GHashTable *optlist;
	void *free_arg;
	char *ptr;
#line 1532 "Core.c"
#line 576 "Core.xs"
	if (cmd_get_params(data, &free_arg, 1 | PARAM_FLAG_OPTIONS | PARAM_FLAG_GETREST,
			   cmd, &optlist, &ptr)) {
		hash = newHV();
		g_hash_table_foreach(optlist, add_tuple, hash);
		XPUSHs(sv_2mortal(newRV_noinc((SV*)hash)));
		XPUSHs(sv_2mortal(new_pv(ptr)));
		cmd_params_free(free_arg);
	} else {
		XPUSHs(&PL_sv_undef);
		XPUSHs(&PL_sv_undef);
	}
#line 1545 "Core.c"
	PUTBACK;
	return;
    }
}


XS(XS_Irssi_pidwait_add); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_pidwait_add)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "pid");
    {
	int	pid = (int)SvIV(ST(0));

	pidwait_add(pid);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi_pidwait_remove); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_pidwait_remove)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "pid");
    {
	int	pid = (int)SvIV(ST(0));

	pidwait_remove(pid);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi_parse_special); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_parse_special)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 1 || items > 3)
       croak_xs_usage(cv,  "cmd, data=\"\", flags=0");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	char *	cmd = (char *)SvPV_nolen(ST(0));
	char *	data;
	int	flags;
#line 602 "Core.xs"
	char *ret;
#line 1608 "Core.c"

	if (items < 2)
	    data = "";
	else {
	    data = (char *)SvPV_nolen(ST(1));
	}

	if (items < 3)
	    flags = 0;
	else {
	    flags = (int)SvIV(ST(2));
	}
#line 604 "Core.xs"
	ret = parse_special_string(cmd, NULL, NULL, data, NULL, flags);
	XPUSHs(sv_2mortal(new_pv(ret)));
	g_free_not_null(ret);
#line 1625 "Core.c"
	PUTBACK;
	return;
    }
}


XS(XS_Irssi_get_irssi_dir); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_get_irssi_dir)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	char *	RETVAL;
	dXSTARG;
#line 611 "Core.xs"
	RETVAL = (char *) get_irssi_dir();
#line 1647 "Core.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Irssi_get_irssi_config); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_get_irssi_config)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	char *	RETVAL;
	dXSTARG;
#line 618 "Core.xs"
	RETVAL = (char *) get_irssi_config();
#line 1669 "Core.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Irssi_get_irssi_binary); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_get_irssi_binary)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	char *	RETVAL;
	dXSTARG;
#line 625 "Core.xs"
	RETVAL = irssi_binary;
#line 1691 "Core.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Irssi_version); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_version)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
#line 632 "Core.xs"
	char version[100];
#line 1711 "Core.c"
	char *	RETVAL;
	dXSTARG;
#line 634 "Core.xs"
	g_snprintf(version, sizeof(version), "%d.%04d",
		   IRSSI_VERSION_DATE, IRSSI_VERSION_TIME);
	RETVAL = version;
#line 1718 "Core.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Irssi_get_gui); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_get_gui)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 643 "Core.xs"
	RETVAL = irssi_gui;
#line 1740 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_IRSSI_GUI_NONE); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_IRSSI_GUI_NONE)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 650 "Core.xs"
	RETVAL = IRSSI_GUI_NONE;
#line 1762 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_IRSSI_GUI_TEXT); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_IRSSI_GUI_TEXT)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 657 "Core.xs"
	RETVAL = IRSSI_GUI_TEXT;
#line 1784 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_IRSSI_GUI_GTK); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_IRSSI_GUI_GTK)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 664 "Core.xs"
	RETVAL = IRSSI_GUI_GTK;
#line 1806 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_IRSSI_GUI_GNOME); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_IRSSI_GUI_GNOME)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 671 "Core.xs"
	RETVAL = IRSSI_GUI_GNOME;
#line 1828 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_IRSSI_GUI_QT); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_IRSSI_GUI_QT)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 678 "Core.xs"
	RETVAL = IRSSI_GUI_QT;
#line 1850 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_IRSSI_GUI_KDE); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_IRSSI_GUI_KDE)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 685 "Core.xs"
	RETVAL = IRSSI_GUI_KDE;
#line 1872 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi__Server_parse_special); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Server_parse_special)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 2 || items > 4)
       croak_xs_usage(cv,  "server, cmd, data=\"\", flags=0");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	Irssi__Server	server = irssi_ref_object(ST(0));
	char *	cmd = (char *)SvPV_nolen(ST(1));
	char *	data;
	int	flags;
#line 700 "Core.xs"
	char *ret;
#line 1898 "Core.c"

	if (items < 3)
	    data = "";
	else {
	    data = (char *)SvPV_nolen(ST(2));
	}

	if (items < 4)
	    flags = 0;
	else {
	    flags = (int)SvIV(ST(3));
	}
#line 702 "Core.xs"
	ret = parse_special_string(cmd, server, NULL, data, NULL, flags);
	XPUSHs(sv_2mortal(new_pv(ret)));
	g_free_not_null(ret);
#line 1915 "Core.c"
	PUTBACK;
	return;
    }
}


XS(XS_Irssi__Server_command); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Server_command)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "server, cmd");
    {
	Irssi__Server	server = irssi_ref_object(ST(0));
	char *	cmd = (char *)SvPV_nolen(ST(1));
#line 711 "Core.xs"
	perl_command(cmd, server, NULL);
#line 1937 "Core.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Windowitem_parse_special); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Windowitem_parse_special)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 2 || items > 4)
       croak_xs_usage(cv,  "item, cmd, data=\"\", flags=0");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	Irssi__Windowitem	item = irssi_ref_object(ST(0));
	char *	cmd = (char *)SvPV_nolen(ST(1));
	char *	data;
	int	flags;
#line 725 "Core.xs"
	char *ret;
#line 1962 "Core.c"

	if (items < 3)
	    data = "";
	else {
	    data = (char *)SvPV_nolen(ST(2));
	}

	if (items < 4)
	    flags = 0;
	else {
	    flags = (int)SvIV(ST(3));
	}
#line 727 "Core.xs"
	ret = parse_special_string(cmd, item->server, item, data, NULL, flags);
	XPUSHs(sv_2mortal(new_pv(ret)));
	g_free_not_null(ret);
#line 1979 "Core.c"
	PUTBACK;
	return;
    }
}


XS(XS_Irssi__Windowitem_command); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Windowitem_command)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "item, cmd");
    {
	Irssi__Windowitem	item = irssi_ref_object(ST(0));
	char *	cmd = (char *)SvPV_nolen(ST(1));
#line 736 "Core.xs"
	perl_command(cmd, item->server, item);
#line 2001 "Core.c"
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Irssi__Core); /* prototype to pass -Wmissing-prototypes */
XS(boot_Irssi__Core)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK ;

        (void)newXSproto_portable("Irssi::signal_emit", XS_Irssi_signal_emit, file, "$;@");
        (void)newXSproto_portable("Irssi::signal_continue", XS_Irssi_signal_continue, file, ";@");
        (void)newXSproto_portable("Irssi::signal_add", XS_Irssi_signal_add, file, ";@");
        (void)newXSproto_portable("Irssi::signal_add_first", XS_Irssi_signal_add_first, file, ";@");
        (void)newXSproto_portable("Irssi::signal_add_last", XS_Irssi_signal_add_last, file, ";@");
        (void)newXSproto_portable("Irssi::signal_add_priority", XS_Irssi_signal_add_priority, file, ";@");
        (void)newXSproto_portable("Irssi::signal_register", XS_Irssi_signal_register, file, ";@");
        (void)newXSproto_portable("Irssi::SIGNAL_PRIORITY_LOW", XS_Irssi_SIGNAL_PRIORITY_LOW, file, "");
        (void)newXSproto_portable("Irssi::SIGNAL_PRIORITY_DEFAULT", XS_Irssi_SIGNAL_PRIORITY_DEFAULT, file, "");
        (void)newXSproto_portable("Irssi::SIGNAL_PRIORITY_HIGH", XS_Irssi_SIGNAL_PRIORITY_HIGH, file, "");
        (void)newXSproto_portable("Irssi::signal_remove", XS_Irssi_signal_remove, file, "$$");
        (void)newXSproto_portable("Irssi::signal_stop", XS_Irssi_signal_stop, file, "");
        (void)newXSproto_portable("Irssi::signal_stop_by_name", XS_Irssi_signal_stop_by_name, file, "$");
        (void)newXSproto_portable("Irssi::signal_get_emitted", XS_Irssi_signal_get_emitted, file, "");
        (void)newXSproto_portable("Irssi::signal_get_emitted_id", XS_Irssi_signal_get_emitted_id, file, "");
        (void)newXSproto_portable("Irssi::timeout_add", XS_Irssi_timeout_add, file, "$$$");
        (void)newXSproto_portable("Irssi::timeout_add_once", XS_Irssi_timeout_add_once, file, "$$$");
        (void)newXSproto_portable("Irssi::timeout_remove", XS_Irssi_timeout_remove, file, "$");
        (void)newXSproto_portable("Irssi::INPUT_READ", XS_Irssi_INPUT_READ, file, "");
        (void)newXSproto_portable("Irssi::INPUT_WRITE", XS_Irssi_INPUT_WRITE, file, "");
        (void)newXSproto_portable("Irssi::input_add", XS_Irssi_input_add, file, "$$$$");
        (void)newXSproto_portable("Irssi::input_remove", XS_Irssi_input_remove, file, "$");
        (void)newXSproto_portable("Irssi::MSGLEVEL_CRAP", XS_Irssi_MSGLEVEL_CRAP, file, "");
        (void)newXSproto_portable("Irssi::MSGLEVEL_MSGS", XS_Irssi_MSGLEVEL_MSGS, file, "");
        (void)newXSproto_portable("Irssi::MSGLEVEL_PUBLIC", XS_Irssi_MSGLEVEL_PUBLIC, file, "");
        (void)newXSproto_portable("Irssi::MSGLEVEL_NOTICES", XS_Irssi_MSGLEVEL_NOTICES, file, "");
        (void)newXSproto_portable("Irssi::MSGLEVEL_SNOTES", XS_Irssi_MSGLEVEL_SNOTES, file, "");
        (void)newXSproto_portable("Irssi::MSGLEVEL_CTCPS", XS_Irssi_MSGLEVEL_CTCPS, file, "");
        (void)newXSproto_portable("Irssi::MSGLEVEL_ACTIONS", XS_Irssi_MSGLEVEL_ACTIONS, file, "");
        (void)newXSproto_portable("Irssi::MSGLEVEL_JOINS", XS_Irssi_MSGLEVEL_JOINS, file, "");
        (void)newXSproto_portable("Irssi::MSGLEVEL_PARTS", XS_Irssi_MSGLEVEL_PARTS, file, "");
        (void)newXSproto_portable("Irssi::MSGLEVEL_QUITS", XS_Irssi_MSGLEVEL_QUITS, file, "");
        (void)newXSproto_portable("Irssi::MSGLEVEL_KICKS", XS_Irssi_MSGLEVEL_KICKS, file, "");
        (void)newXSproto_portable("Irssi::MSGLEVEL_MODES", XS_Irssi_MSGLEVEL_MODES, file, "");
        (void)newXSproto_portable("Irssi::MSGLEVEL_TOPICS", XS_Irssi_MSGLEVEL_TOPICS, file, "");
        (void)newXSproto_portable("Irssi::MSGLEVEL_WALLOPS", XS_Irssi_MSGLEVEL_WALLOPS, file, "");
        (void)newXSproto_portable("Irssi::MSGLEVEL_INVITES", XS_Irssi_MSGLEVEL_INVITES, file, "");
        (void)newXSproto_portable("Irssi::MSGLEVEL_NICKS", XS_Irssi_MSGLEVEL_NICKS, file, "");
        (void)newXSproto_portable("Irssi::MSGLEVEL_DCC", XS_Irssi_MSGLEVEL_DCC, file, "");
        (void)newXSproto_portable("Irssi::MSGLEVEL_DCCMSGS", XS_Irssi_MSGLEVEL_DCCMSGS, file, "");
        (void)newXSproto_portable("Irssi::MSGLEVEL_CLIENTNOTICE", XS_Irssi_MSGLEVEL_CLIENTNOTICE, file, "");
        (void)newXSproto_portable("Irssi::MSGLEVEL_CLIENTCRAP", XS_Irssi_MSGLEVEL_CLIENTCRAP, file, "");
        (void)newXSproto_portable("Irssi::MSGLEVEL_CLIENTERROR", XS_Irssi_MSGLEVEL_CLIENTERROR, file, "");
        (void)newXSproto_portable("Irssi::MSGLEVEL_HILIGHT", XS_Irssi_MSGLEVEL_HILIGHT, file, "");
        (void)newXSproto_portable("Irssi::MSGLEVEL_ALL", XS_Irssi_MSGLEVEL_ALL, file, "");
        (void)newXSproto_portable("Irssi::MSGLEVEL_NOHILIGHT", XS_Irssi_MSGLEVEL_NOHILIGHT, file, "");
        (void)newXSproto_portable("Irssi::MSGLEVEL_NO_ACT", XS_Irssi_MSGLEVEL_NO_ACT, file, "");
        (void)newXSproto_portable("Irssi::MSGLEVEL_NEVER", XS_Irssi_MSGLEVEL_NEVER, file, "");
        (void)newXSproto_portable("Irssi::MSGLEVEL_LASTLOG", XS_Irssi_MSGLEVEL_LASTLOG, file, "");
        (void)newXSproto_portable("Irssi::level2bits", XS_Irssi_level2bits, file, "$");
        (void)newXSproto_portable("Irssi::bits2level", XS_Irssi_bits2level, file, "$");
        (void)newXSproto_portable("Irssi::combine_level", XS_Irssi_combine_level, file, "$$");
        (void)newXSproto_portable("Irssi::command", XS_Irssi_command, file, "$");
        (void)newXSproto_portable("Irssi::commands", XS_Irssi_commands, file, "");
        (void)newXSproto_portable("Irssi::command_bind_first", XS_Irssi_command_bind_first, file, ";@");
        (void)newXSproto_portable("Irssi::command_bind", XS_Irssi_command_bind, file, ";@");
        (void)newXSproto_portable("Irssi::command_bind_last", XS_Irssi_command_bind_last, file, ";@");
        (void)newXSproto_portable("Irssi::command_runsub", XS_Irssi_command_runsub, file, "$$$$");
        (void)newXSproto_portable("Irssi::command_unbind", XS_Irssi_command_unbind, file, "$$");
        (void)newXSproto_portable("Irssi::command_set_options", XS_Irssi_command_set_options, file, "$$");
        (void)newXSproto_portable("Irssi::command_parse_options", XS_Irssi_command_parse_options, file, "$$");
        (void)newXSproto_portable("Irssi::pidwait_add", XS_Irssi_pidwait_add, file, "$");
        (void)newXSproto_portable("Irssi::pidwait_remove", XS_Irssi_pidwait_remove, file, "$");
        (void)newXSproto_portable("Irssi::parse_special", XS_Irssi_parse_special, file, "$;$$");
        (void)newXSproto_portable("Irssi::get_irssi_dir", XS_Irssi_get_irssi_dir, file, "");
        (void)newXSproto_portable("Irssi::get_irssi_config", XS_Irssi_get_irssi_config, file, "");
        (void)newXSproto_portable("Irssi::get_irssi_binary", XS_Irssi_get_irssi_binary, file, "");
        (void)newXSproto_portable("Irssi::version", XS_Irssi_version, file, "");
        (void)newXSproto_portable("Irssi::get_gui", XS_Irssi_get_gui, file, "");
        (void)newXSproto_portable("Irssi::IRSSI_GUI_NONE", XS_Irssi_IRSSI_GUI_NONE, file, "");
        (void)newXSproto_portable("Irssi::IRSSI_GUI_TEXT", XS_Irssi_IRSSI_GUI_TEXT, file, "");
        (void)newXSproto_portable("Irssi::IRSSI_GUI_GTK", XS_Irssi_IRSSI_GUI_GTK, file, "");
        (void)newXSproto_portable("Irssi::IRSSI_GUI_GNOME", XS_Irssi_IRSSI_GUI_GNOME, file, "");
        (void)newXSproto_portable("Irssi::IRSSI_GUI_QT", XS_Irssi_IRSSI_GUI_QT, file, "");
        (void)newXSproto_portable("Irssi::IRSSI_GUI_KDE", XS_Irssi_IRSSI_GUI_KDE, file, "");
        (void)newXSproto_portable("Irssi::Server::parse_special", XS_Irssi__Server_parse_special, file, "$$;$$");
        (void)newXSproto_portable("Irssi::Server::command", XS_Irssi__Server_command, file, "$$");
        (void)newXSproto_portable("Irssi::Windowitem::parse_special", XS_Irssi__Windowitem_parse_special, file, "$$;$$");
        (void)newXSproto_portable("Irssi::Windowitem::command", XS_Irssi__Windowitem_command, file, "$$");
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

