/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2210 from the
 * contents of Ignore.xs. Do not edit this file, edit Ignore.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Ignore.xs"
#include "module.h"

#line 13 "Ignore.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 65 "Ignore.c"

XS(XS_Irssi_ignores); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_ignores)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 9 "Ignore.xs"
	GSList *tmp;
#line 82 "Ignore.c"
#line 11 "Ignore.xs"
	for (tmp = ignores; tmp != NULL; tmp = tmp->next) {
		XPUSHs(sv_2mortal(plain_bless(tmp->data, "Irssi::Ignore")));
	}
#line 87 "Ignore.c"
	PUTBACK;
	return;
    }
}


XS(XS_Irssi_ignore_check); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_ignore_check)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 5)
       croak_xs_usage(cv,  "nick, host, channel, text, level");
    {
	char *	nick = (char *)SvPV_nolen(ST(0));
	char *	host = (char *)SvPV_nolen(ST(1));
	char *	channel = (char *)SvPV_nolen(ST(2));
	char *	text = (char *)SvPV_nolen(ST(3));
	int	level = (int)SvIV(ST(4));
	int	RETVAL;
	dXSTARG;
#line 23 "Ignore.xs"
	RETVAL = ignore_check(NULL, nick, host, channel, text, level);
#line 114 "Ignore.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi__Server_ignore_check); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Server_ignore_check)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 6)
       croak_xs_usage(cv,  "server, nick, host, channel, text, level");
    {
	Irssi__Server	server = irssi_ref_object(ST(0));
	char *	nick = (char *)SvPV_nolen(ST(1));
	char *	host = (char *)SvPV_nolen(ST(2));
	char *	channel = (char *)SvPV_nolen(ST(3));
	char *	text = (char *)SvPV_nolen(ST(4));
	int	level = (int)SvIV(ST(5));
	int	RETVAL;
	dXSTARG;

	RETVAL = ignore_check(server, nick, host, channel, text, level);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi__Ignore_add_rec); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Ignore_add_rec)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "rec");
    {
	Irssi__Ignore	rec = irssi_ref_object(ST(0));

	ignore_add_rec(rec);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Ignore_update_rec); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Ignore_update_rec)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "rec");
    {
	Irssi__Ignore	rec = irssi_ref_object(ST(0));

	ignore_update_rec(rec);
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Irssi__Ignore); /* prototype to pass -Wmissing-prototypes */
XS(boot_Irssi__Ignore)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK ;

        (void)newXSproto_portable("Irssi::ignores", XS_Irssi_ignores, file, "");
        (void)newXSproto_portable("Irssi::ignore_check", XS_Irssi_ignore_check, file, "$$$$$");
        (void)newXSproto_portable("Irssi::Server::ignore_check", XS_Irssi__Server_ignore_check, file, "$$$$$$");
        (void)newXSproto_portable("Irssi::Ignore::add_rec", XS_Irssi__Ignore_add_rec, file, "$");
        (void)newXSproto_portable("Irssi::Ignore::update_rec", XS_Irssi__Ignore_update_rec, file, "$");
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

