/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2210 from the
 * contents of Log.xs. Do not edit this file, edit Log.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Log.xs"
#include "module.h"

#line 13 "Log.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 65 "Log.c"

XS(XS_Irssi_logs); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_logs)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 9 "Log.xs"
	GSList *tmp;
#line 82 "Log.c"
#line 11 "Log.xs"
	for (tmp = logs; tmp != NULL; tmp = tmp->next) {
		XPUSHs(sv_2mortal(plain_bless(tmp->data, "Irssi::Log")));
	}
#line 87 "Log.c"
	PUTBACK;
	return;
    }
}


XS(XS_Irssi_log_create_rec); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_log_create_rec)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "fname, level");
    {
	char *	fname = (char *)SvPV_nolen(ST(0));
	int	level = (int)SvIV(ST(1));
	Irssi__Log	RETVAL;

	RETVAL = log_create_rec(fname, level);
	ST(0) = plain_bless(RETVAL, "Irssi::Log");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi_log_find); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_log_find)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "fname");
    {
	char *	fname = (char *)SvPV_nolen(ST(0));
	Irssi__Log	RETVAL;

	RETVAL = log_find(fname);
	ST(0) = plain_bless(RETVAL, "Irssi::Log");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi__Log_item_add); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Log_item_add)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 4)
       croak_xs_usage(cv,  "log, type, name, servertag");
    {
	Irssi__Log	log = irssi_ref_object(ST(0));
	int	type = (int)SvIV(ST(1));
	char *	name = (char *)SvPV_nolen(ST(2));
	char *	servertag = (char *)SvPV_nolen(ST(3));

	log_item_add(log, type, name, servertag);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Log_item_destroy); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Log_item_destroy)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "log, item");
    {
	Irssi__Log	log = irssi_ref_object(ST(0));
	Irssi__Logitem	item = irssi_ref_object(ST(1));

	log_item_destroy(log, item);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Log_item_find); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Log_item_find)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 4)
       croak_xs_usage(cv,  "log, type, item, servertag");
    {
	Irssi__Log	log = irssi_ref_object(ST(0));
	int	type = (int)SvIV(ST(1));
	char *	item = (char *)SvPV_nolen(ST(2));
	char *	servertag = (char *)SvPV_nolen(ST(3));
	Irssi__Logitem	RETVAL;

	RETVAL = log_item_find(log, type, item, servertag);
	ST(0) = plain_bless(RETVAL, "Irssi::Logitem");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi__Log_update); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Log_update)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "log");
    {
	Irssi__Log	log = irssi_ref_object(ST(0));

	log_update(log);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Log_close); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Log_close)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "log");
    {
	Irssi__Log	log = irssi_ref_object(ST(0));

	log_close(log);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Log_write_rec); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Log_write_rec)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       croak_xs_usage(cv,  "log, str, level");
    {
	Irssi__Log	log = irssi_ref_object(ST(0));
	char *	str = (char *)SvPV_nolen(ST(1));
	int	level = (int)SvIV(ST(2));

	log_write_rec(log, str, level);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Log_start_logging); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Log_start_logging)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "log");
    {
	Irssi__Log	log = irssi_ref_object(ST(0));

	log_start_logging(log);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Log_stop_logging); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Log_stop_logging)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "log");
    {
	Irssi__Log	log = irssi_ref_object(ST(0));

	log_stop_logging(log);
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Irssi__Log); /* prototype to pass -Wmissing-prototypes */
XS(boot_Irssi__Log)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK ;

        (void)newXSproto_portable("Irssi::logs", XS_Irssi_logs, file, "");
        (void)newXSproto_portable("Irssi::log_create_rec", XS_Irssi_log_create_rec, file, "$$");
        (void)newXSproto_portable("Irssi::log_find", XS_Irssi_log_find, file, "$");
        (void)newXSproto_portable("Irssi::Log::item_add", XS_Irssi__Log_item_add, file, "$$$$");
        (void)newXSproto_portable("Irssi::Log::item_destroy", XS_Irssi__Log_item_destroy, file, "$$");
        (void)newXSproto_portable("Irssi::Log::item_find", XS_Irssi__Log_item_find, file, "$$$$");
        (void)newXSproto_portable("Irssi::Log::update", XS_Irssi__Log_update, file, "$");
        (void)newXSproto_portable("Irssi::Log::close", XS_Irssi__Log_close, file, "$");
        (void)newXSproto_portable("Irssi::Log::write_rec", XS_Irssi__Log_write_rec, file, "$$$");
        (void)newXSproto_portable("Irssi::Log::start_logging", XS_Irssi__Log_start_logging, file, "$");
        (void)newXSproto_portable("Irssi::Log::stop_logging", XS_Irssi__Log_stop_logging, file, "$");
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

