/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2210 from the
 * contents of Query.xs. Do not edit this file, edit Query.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Query.xs"
#include "module.h"

#line 13 "Query.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 65 "Query.c"

XS(XS_Irssi_queries); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_queries)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 9 "Query.xs"
	GSList *tmp;
#line 82 "Query.c"
#line 11 "Query.xs"
	for (tmp = queries; tmp != NULL; tmp = tmp->next) {
		QUERY_REC *rec = tmp->data;

		XPUSHs(sv_2mortal(iobject_bless(rec)));
	}
#line 89 "Query.c"
	PUTBACK;
	return;
    }
}


XS(XS_Irssi_query_find); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_query_find)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "nick");
    {
	char *	nick = (char *)SvPV_nolen(ST(0));
	Irssi__Query	RETVAL;
#line 21 "Query.xs"
	RETVAL = query_find(NULL, nick);
#line 111 "Query.c"
	ST(0) = iobject_bless((SERVER_REC *)RETVAL);

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi__Server_queries); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Server_queries)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "server");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	Irssi__Server	server = irssi_ref_object(ST(0));
#line 33 "Query.xs"
	GSList *tmp;
#line 136 "Query.c"
#line 35 "Query.xs"
	for (tmp = server->queries; tmp != NULL; tmp = tmp->next) {
		QUERY_REC *rec = tmp->data;

		XPUSHs(sv_2mortal(iobject_bless(rec)));
	}
#line 143 "Query.c"
	PUTBACK;
	return;
    }
}


XS(XS_Irssi__Server_query_find); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Server_query_find)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "server, nick");
    {
	Irssi__Server	server = irssi_ref_object(ST(0));
	char *	nick = (char *)SvPV_nolen(ST(1));
	Irssi__Query	RETVAL;

	RETVAL = query_find(server, nick);
	ST(0) = iobject_bless((SERVER_REC *)RETVAL);

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi__Query_destroy); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Query_destroy)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "query");
    {
	Irssi__Query	query = irssi_ref_object(ST(0));

	query_destroy(query);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Query_change_server); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Query_change_server)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "query, server");
    {
	Irssi__Query	query = irssi_ref_object(ST(0));
	Irssi__Server	server = irssi_ref_object(ST(1));

	query_change_server(query, server);
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Irssi__Query); /* prototype to pass -Wmissing-prototypes */
XS(boot_Irssi__Query)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK ;

        (void)newXSproto_portable("Irssi::queries", XS_Irssi_queries, file, "");
        (void)newXSproto_portable("Irssi::query_find", XS_Irssi_query_find, file, "$");
        (void)newXSproto_portable("Irssi::Server::queries", XS_Irssi__Server_queries, file, "$");
        (void)newXSproto_portable("Irssi::Server::query_find", XS_Irssi__Server_query_find, file, "$$");
        (void)newXSproto_portable("Irssi::Query::destroy", XS_Irssi__Query_destroy, file, "$");
        (void)newXSproto_portable("Irssi::Query::change_server", XS_Irssi__Query_change_server, file, "$$");
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

