/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2210 from the
 * contents of Rawlog.xs. Do not edit this file, edit Rawlog.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Rawlog.xs"
#include "module.h"

#line 13 "Rawlog.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 65 "Rawlog.c"

XS(XS_Irssi_rawlog_set_size); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_rawlog_set_size)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "lines");
    {
	int	lines = (int)SvIV(ST(0));

	rawlog_set_size(lines);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi_rawlog_create); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_rawlog_create)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	Irssi__Rawlog	RETVAL;

	RETVAL = rawlog_create();
	ST(0) = plain_bless(RETVAL, "Irssi::Rawlog");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi__Rawlog_get_lines); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Rawlog_get_lines)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "rawlog");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	Irssi__Rawlog	rawlog = irssi_ref_object(ST(0));
#line 21 "Rawlog.xs"
	GSList *tmp;
#line 124 "Rawlog.c"
#line 23 "Rawlog.xs"
	for (tmp = rawlog->lines; tmp != NULL; tmp = tmp->next) {
		XPUSHs(sv_2mortal(new_pv(tmp->data)));
	}
#line 129 "Rawlog.c"
	PUTBACK;
	return;
    }
}


XS(XS_Irssi__Rawlog_destroy); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Rawlog_destroy)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "rawlog");
    {
	Irssi__Rawlog	rawlog = irssi_ref_object(ST(0));

	rawlog_destroy(rawlog);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Rawlog_input); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Rawlog_input)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "rawlog, str");
    {
	Irssi__Rawlog	rawlog = irssi_ref_object(ST(0));
	char *	str = (char *)SvPV_nolen(ST(1));

	rawlog_input(rawlog, str);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Rawlog_output); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Rawlog_output)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "rawlog, str");
    {
	Irssi__Rawlog	rawlog = irssi_ref_object(ST(0));
	char *	str = (char *)SvPV_nolen(ST(1));

	rawlog_output(rawlog, str);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Rawlog_redirect); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Rawlog_redirect)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "rawlog, str");
    {
	Irssi__Rawlog	rawlog = irssi_ref_object(ST(0));
	char *	str = (char *)SvPV_nolen(ST(1));

	rawlog_redirect(rawlog, str);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Rawlog_open); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Rawlog_open)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "rawlog, fname");
    {
	Irssi__Rawlog	rawlog = irssi_ref_object(ST(0));
	char *	fname = (char *)SvPV_nolen(ST(1));

	rawlog_open(rawlog, fname);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Rawlog_close); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Rawlog_close)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "rawlog");
    {
	Irssi__Rawlog	rawlog = irssi_ref_object(ST(0));

	rawlog_close(rawlog);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Rawlog_save); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Rawlog_save)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "rawlog, fname");
    {
	Irssi__Rawlog	rawlog = irssi_ref_object(ST(0));
	char *	fname = (char *)SvPV_nolen(ST(1));

	rawlog_save(rawlog, fname);
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Irssi__Rawlog); /* prototype to pass -Wmissing-prototypes */
XS(boot_Irssi__Rawlog)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK ;

        (void)newXSproto_portable("Irssi::rawlog_set_size", XS_Irssi_rawlog_set_size, file, "$");
        (void)newXSproto_portable("Irssi::rawlog_create", XS_Irssi_rawlog_create, file, "");
        (void)newXSproto_portable("Irssi::Rawlog::get_lines", XS_Irssi__Rawlog_get_lines, file, "$");
        (void)newXSproto_portable("Irssi::Rawlog::destroy", XS_Irssi__Rawlog_destroy, file, "$");
        (void)newXSproto_portable("Irssi::Rawlog::input", XS_Irssi__Rawlog_input, file, "$$");
        (void)newXSproto_portable("Irssi::Rawlog::output", XS_Irssi__Rawlog_output, file, "$$");
        (void)newXSproto_portable("Irssi::Rawlog::redirect", XS_Irssi__Rawlog_redirect, file, "$$");
        (void)newXSproto_portable("Irssi::Rawlog::open", XS_Irssi__Rawlog_open, file, "$$");
        (void)newXSproto_portable("Irssi::Rawlog::close", XS_Irssi__Rawlog_close, file, "$");
        (void)newXSproto_portable("Irssi::Rawlog::save", XS_Irssi__Rawlog_save, file, "$$");
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

