/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2210 from the
 * contents of Server.xs. Do not edit this file, edit Server.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Server.xs"
#include "module.h"

#line 13 "Server.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 65 "Server.c"

XS(XS_Irssi_servers); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_servers)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 9 "Server.xs"
	GSList *tmp;
#line 82 "Server.c"
#line 11 "Server.xs"
	for (tmp = servers; tmp != NULL; tmp = tmp->next) {
		XPUSHs(sv_2mortal(iobject_bless((SERVER_REC *) tmp->data)));
	}
#line 87 "Server.c"
	PUTBACK;
	return;
    }
}


XS(XS_Irssi_reconnects); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_reconnects)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 18 "Server.xs"
	GSList *tmp;
#line 109 "Server.c"
#line 20 "Server.xs"
	for (tmp = reconnects; tmp != NULL; tmp = tmp->next) {
		XPUSHs(sv_2mortal(plain_bless(tmp->data, "Irssi::Reconnect")));
	}
#line 114 "Server.c"
	PUTBACK;
	return;
    }
}


XS(XS_Irssi_chatnets); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_chatnets)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 27 "Server.xs"
	GSList *tmp;
#line 136 "Server.c"
#line 29 "Server.xs"
	for (tmp = chatnets; tmp != NULL; tmp = tmp->next) {
		XPUSHs(sv_2mortal(iobject_bless((CHATNET_REC *) tmp->data)));
	}
#line 141 "Server.c"
	PUTBACK;
	return;
    }
}


XS(XS_Irssi_server_create_conn); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_server_create_conn)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 3 || items > 6)
       croak_xs_usage(cv,  "chat_type, dest, port, chatnet=NULL, password=NULL, nick=NULL");
    {
	int	chat_type = (int)SvIV(ST(0));
	char *	dest = (char *)SvPV_nolen(ST(1));
	int	port = (int)SvIV(ST(2));
	char *	chatnet;
	char *	password;
	char *	nick;
	Irssi__Connect	RETVAL;

	if (items < 4)
	    chatnet = NULL;
	else {
	    chatnet = (char *)SvPV_nolen(ST(3));
	}

	if (items < 5)
	    password = NULL;
	else {
	    password = (char *)SvPV_nolen(ST(4));
	}

	if (items < 6)
	    nick = NULL;
	else {
	    nick = (char *)SvPV_nolen(ST(5));
	}

	RETVAL = server_create_conn(chat_type, dest, port, chatnet, password, nick);
	ST(0) = iobject_bless((SERVER_REC *)RETVAL);

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi_server_find_tag); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_server_find_tag)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "tag");
    {
	char *	tag = (char *)SvPV_nolen(ST(0));
	Irssi__Server	RETVAL;

	RETVAL = server_find_tag(tag);
	ST(0) = iobject_bless((SERVER_REC *)RETVAL);

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi_server_find_chatnet); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_server_find_chatnet)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "chatnet");
    {
	char *	chatnet = (char *)SvPV_nolen(ST(0));
	Irssi__Server	RETVAL;

	RETVAL = server_find_chatnet(chatnet);
	ST(0) = iobject_bless((SERVER_REC *)RETVAL);

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi_chatnet_find); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_chatnet_find)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "name");
    {
	char *	name = (char *)SvPV_nolen(ST(0));
	Irssi__Chatnet	RETVAL;

	RETVAL = chatnet_find(name);
	ST(0) = iobject_bless((SERVER_REC *)RETVAL);

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi__Server_disconnect); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Server_disconnect)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "server");
    {
	Irssi__Server	server = irssi_ref_object(ST(0));

	server_disconnect(server);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Server_ref); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Server_ref)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "server");
    {
	Irssi__Server	server = irssi_ref_object(ST(0));

	server_ref(server);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Server_unref); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Server_unref)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "server");
    {
	Irssi__Server	server = irssi_ref_object(ST(0));

	server_unref(server);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Server_isnickflag); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Server_isnickflag)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "server, flag");
    {
	Irssi__Server	server = irssi_ref_object(ST(0));
	char	flag = (char)*SvPV_nolen(ST(1));
	int	RETVAL;
	dXSTARG;
#line 75 "Server.xs"
	RETVAL = server->isnickflag(server, flag);
#line 337 "Server.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi__Server_ischannel); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Server_ischannel)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "server, data");
    {
	Irssi__Server	server = irssi_ref_object(ST(0));
	char *	data = (char *)SvPV_nolen(ST(1));
	int	RETVAL;
	dXSTARG;
#line 84 "Server.xs"
	RETVAL = server->ischannel(server, data);
#line 361 "Server.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi__Server_get_nick_flags); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Server_get_nick_flags)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "server");
    {
	Irssi__Server	server = irssi_ref_object(ST(0));
	char *	RETVAL;
	dXSTARG;
#line 92 "Server.xs"
	RETVAL = (char *) server->get_nick_flags(server);
#line 384 "Server.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Irssi__Server_send_message); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Server_send_message)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 4)
       croak_xs_usage(cv,  "server, target, msg, target_type");
    {
	Irssi__Server	server = irssi_ref_object(ST(0));
	char *	target = (char *)SvPV_nolen(ST(1));
	char *	msg = (char *)SvPV_nolen(ST(2));
	int	target_type = (int)SvIV(ST(3));
#line 103 "Server.xs"
	server->send_message(server, target, msg, target_type);
#line 408 "Server.c"
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Irssi__Server); /* prototype to pass -Wmissing-prototypes */
XS(boot_Irssi__Server)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK ;

        (void)newXSproto_portable("Irssi::servers", XS_Irssi_servers, file, "");
        (void)newXSproto_portable("Irssi::reconnects", XS_Irssi_reconnects, file, "");
        (void)newXSproto_portable("Irssi::chatnets", XS_Irssi_chatnets, file, "");
        (void)newXSproto_portable("Irssi::server_create_conn", XS_Irssi_server_create_conn, file, "$$$;$$$");
        (void)newXSproto_portable("Irssi::server_find_tag", XS_Irssi_server_find_tag, file, "$");
        (void)newXSproto_portable("Irssi::server_find_chatnet", XS_Irssi_server_find_chatnet, file, "$");
        (void)newXSproto_portable("Irssi::chatnet_find", XS_Irssi_chatnet_find, file, "$");
        (void)newXSproto_portable("Irssi::Server::disconnect", XS_Irssi__Server_disconnect, file, "$");
        (void)newXSproto_portable("Irssi::Server::ref", XS_Irssi__Server_ref, file, "$");
        (void)newXSproto_portable("Irssi::Server::unref", XS_Irssi__Server_unref, file, "$");
        (void)newXSproto_portable("Irssi::Server::isnickflag", XS_Irssi__Server_isnickflag, file, "$$");
        (void)newXSproto_portable("Irssi::Server::ischannel", XS_Irssi__Server_ischannel, file, "$$");
        (void)newXSproto_portable("Irssi::Server::get_nick_flags", XS_Irssi__Server_get_nick_flags, file, "$");
        (void)newXSproto_portable("Irssi::Server::send_message", XS_Irssi__Server_send_message, file, "$$$$");
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

